import Fastify from 'fastify';
import makeWASocket,{DisconnectReason,fetchLatestBaileysVersion,useMultiFileAuthState} from 'baileys';
import pino from 'pino';

const PORT=Number(process.env.PORT??3010);const HOST=process.env.HOST??'0.0.0.0';const PROVIDER_TOKEN=process.env.WHATSAPP_PROVIDER_TOKEN??'';const AUTH_DIR=process.env.WHATSAPP_AUTH_DIR??'/data/auth';const PAIRING_PHONE=(process.env.WHATSAPP_PAIRING_PHONE??'').replace(/\D/g,'');const logger=pino({level:process.env.LOG_LEVEL??'info'});
let sock:ReturnType<typeof makeWASocket>|null=null;let connected=false;let registered=false;let pairingCode:string|null=null;let reconnecting=false;
const authorized=(h:string|undefined)=>Boolean(PROVIDER_TOKEN)&&h===`Bearer ${PROVIDER_TOKEN}`;
async function connect(){if(reconnecting)return;reconnecting=true;try{const{state,saveCreds}=await useMultiFileAuthState(AUTH_DIR);registered=Boolean(state.creds.registered);const{version}=await fetchLatestBaileysVersion();const current=makeWASocket({version,auth:state,logger,markOnlineOnConnect:false,syncFullHistory:false});sock=current;current.ev.on('creds.update',async u=>{if(typeof u.registered==='boolean')registered=u.registered;await saveCreds()});current.ev.on('connection.update',async u=>{if(u.connection==='open'){connected=true;registered=true;pairingCode=null;logger.info('WhatsApp connected')}if(u.connection==='close'){connected=false;const status=(u.lastDisconnect?.error as any)?.output?.statusCode;const loggedOut=status===DisconnectReason.loggedOut;logger.warn({status,loggedOut},'WhatsApp closed');if(!loggedOut)setTimeout(()=>{reconnecting=false;void connect()},3000)}if(u.qr&&!registered&&PAIRING_PHONE&&!pairingCode)try{pairingCode=await current.requestPairingCode(PAIRING_PHONE)}catch(e){logger.warn({e},'pairing code not ready')}});if(!registered&&PAIRING_PHONE&&!pairingCode)try{pairingCode=await current.requestPairingCode(PAIRING_PHONE)}catch(e){logger.warn({e},'pairing code not ready')}}finally{reconnecting=false}}
const app=Fastify({logger});
app.get('/health',async()=>({status:connected?'ok':'degraded',connected,paired:registered}));
app.get('/pairing-code',async(req,reply)=>{if(!authorized(req.headers.authorization))return reply.code(401).send({error:'unauthorized'});if(registered)return{paired:true,pairingCode:null};if(!pairingCode&&PAIRING_PHONE&&sock)pairingCode=await sock.requestPairingCode(PAIRING_PHONE);return{paired:false,pairingCode,phone:PAIRING_PHONE?`${PAIRING_PHONE.slice(0,4)}***`:null}});
app.post('/send',async(req,reply)=>{if(!authorized(req.headers.authorization))return reply.code(401).send({error:'unauthorized'});const b=req.body as{to?:string;text?:string};if(!b?.to||!b?.text)return reply.code(400).send({error:'to and text required'});if(!connected||!sock)return reply.code(503).send({error:'WhatsApp is not connected'});const digits=b.to.replace(/\D/g,'');if(digits.length<8)return reply.code(400).send({error:'invalid phone'});const result=await sock.sendMessage(`${digits}@s.whatsapp.net`,{text:b.text});return{id:result?.key?.id??null,to:digits,status:'sent'}});
void connect();await app.listen({port:PORT,host:HOST});
