import type pg from 'pg';
import { sendExternal, ProviderUnavailable, type ExternalChannel } from './providers.js';
import { workerPool, workerTx } from './db.js';
import { workerConfig } from './config.js';

export type OutboxEvent={id:number;topic:string;aggregate_type:string|null;aggregate_id:string|null;payload:any;attempt_count:number};
type Channel='EMAIL'|'WHATSAPP'|'TELEGRAM';
type Target={userId?:string;email?:string|null;phone?:string|null;title:string;body:string;category:string;priority?:'LOW'|'NORMAL'|'HIGH'|'CRITICAL';actionUrl?:string;primary:Channel[];fallback?:Partial<Record<Channel,Channel>>;dedupe:string;mandatory?:boolean};

async function userTarget(client:pg.PoolClient,userId:string){const u=await client.query(`select email,full_name from users where id=$1`,[userId]);return u.rows[0]??{};}
async function classStudents(client:pg.PoolClient,classId:string){return (await client.query(`select u.id,u.email from enrollments e join users u on u.id=e.student_user_id where e.class_id=$1 and e.status='active' and u.is_active=true`,[classId])).rows;}

export async function resolveTargets(client:pg.PoolClient,event:OutboxEvent):Promise<Target[]>{
  const p=event.payload??{};
  if(event.topic==='assignment.created'||event.topic==='assignment.reminder'){
    const id=p.assignmentId??p.id??event.aggregate_id;const a=await client.query(`select a.id,a.title,a.due_at,a.class_id,c.name class_name from assignments a join classes c on c.id=a.class_id where a.id=$1`,[id]);if(!a.rowCount)return[];const row=a.rows[0];const users=await classStudents(client,row.class_id);const reminder=event.topic==='assignment.reminder';
    return users.map(u=>({userId:u.id,email:u.email,title:reminder?`Reminder tugas: ${row.title}`:`Tugas baru: ${row.title}`,body:reminder?`Deadline ${row.title} sekitar ${p.hoursBefore} jam lagi.`:`Tugas ${row.title} untuk ${row.class_name}${row.due_at?` memiliki deadline ${new Date(row.due_at).toLocaleString('id-ID')}`:''}.`,category:'academic',actionUrl:`/assignments/${row.id}`,primary:['WHATSAPP'],fallback:{WHATSAPP:'TELEGRAM',TELEGRAM:'EMAIL'},dedupe:reminder?`assignment-reminder:${row.id}:${p.hoursBefore}:${u.id}`:`assignment:${row.id}:${u.id}`}));
  }
  if(event.topic==='assignment.missing'){
    const u=await userTarget(client,p.userId);return [{userId:p.userId,email:u.email,title:`Tugas belum dikumpulkan: ${p.title}`,body:`Deadline tugas ${p.title} sudah lewat dan belum ada submission. Buka dashboard untuk menindaklanjuti.`,category:'academic',priority:'HIGH',actionUrl:`/assignments/${p.assignmentId}`,primary:['WHATSAPP'],fallback:{WHATSAPP:'TELEGRAM'},dedupe:`missing:${p.assignmentId}:${p.userId}`}];
  }
  if(event.topic==='submission.changed'){
    if(!['submitted','resubmitted'].includes(String(p.status)))return[];const r=await client.query(`select c.teacher_user_id,a.title,u.full_name student_name from submissions s join assignments a on a.id=s.assignment_id join classes c on c.id=a.class_id join users u on u.id=s.student_user_id where s.id=$1`,[p.id??event.aggregate_id]);if(!r.rowCount||!r.rows[0].teacher_user_id)return[];const t=r.rows[0];const u=await userTarget(client,t.teacher_user_id);return [{userId:t.teacher_user_id,email:u.email,title:p.status==='resubmitted'?'Revisi dikirim ulang':'Submission baru',body:`${t.student_name} mengirim ${t.title}.`,category:'academic',primary:[],actionUrl:'/submissions',dedupe:`submission:${p.id}:${p.status}:${p.updated_at??event.id}`}];
  }
  if(event.topic==='grade.changed'){
    const r=await client.query(`select s.student_user_id,a.title from grades g join submissions s on s.id=g.submission_id join assignments a on a.id=s.assignment_id where g.id=$1`,[p.id??event.aggregate_id]);if(!r.rowCount)return[];const row=r.rows[0];const u=await userTarget(client,row.student_user_id);const revision=Boolean(p.revision_required);return [{userId:row.student_user_id,email:u.email,title:revision?'Revisi diperlukan':`Nilai tersedia: ${row.title}`,body:revision?`Ustadz meminta revisi untuk ${row.title}. Buka dashboard untuk melihat feedback dan deadline revisi.`:`Nilai ${row.title}: ${p.score}. Buka dashboard untuk melihat feedback.`,category:'academic',actionUrl:'/grades',primary:['WHATSAPP'],fallback:{WHATSAPP:'TELEGRAM',TELEGRAM:'EMAIL'},dedupe:`grade:${p.id}:${p.updated_at??p.graded_at??event.id}`}];
  }
  if(event.topic==='certificate.issued'){const u=await userTarget(client,p.student_user_id);return [{userId:p.student_user_id,email:u.email,title:'Sertifikat baru',body:`Sertifikat ${p.title} telah diterbitkan dan tersedia di dashboard PMMI.`,category:'certificate',actionUrl:'/certificates',primary:['EMAIL','WHATSAPP'],fallback:{WHATSAPP:'TELEGRAM'},dedupe:`certificate:${p.id}`,mandatory:true}];}
  if(event.topic==='portfolio.featured')return [{userId:p.student_user_id,title:'Karyamu masuk portfolio PMMI',body:`${p.title} telah dipilih ustadz/admin sebagai Featured dan langsung dipublikasikan di portfolio PMMI.`,category:'portfolio',actionUrl:`/portfolio/${p.slug}`,primary:[],dedupe:`portfolio:${p.id}`}];
  if(event.topic==='reward.achievement_unlocked'){const u=await userTarget(client,p.userId);return [{userId:p.userId,email:u.email,title:`Achievement: ${p.rewardName}`,body:`Kamu mendapat achievement ${p.rewardName}.${p.aiCredits?` +${p.aiCredits} AI credits.`:''}${p.hermesSlots?` +${p.hermesSlots} slot AI Agent.`:''}`,category:'reward',primary:['WHATSAPP'],fallback:{WHATSAPP:'TELEGRAM'},dedupe:`reward:${p.achievementId}`}];}
  if(event.topic==='onboarding.enrolled')return [{userId:p.userId,email:p.email,title:'Akun PMMI Digital Campus siap diaktifkan',body:`Registrasi selesai. Nomor santri: ${p.studentNumber}. Gunakan tautan aktivasi yang diberikan admin untuk membuat password.`,category:'admission',primary:['EMAIL','WHATSAPP'],fallback:{WHATSAPP:'TELEGRAM'},dedupe:`onboarding:${p.applicationId}`,mandatory:true}];
  if(event.topic.startsWith('admission.')){
    let email=p.email,phone=p.phone,name=p.applicantName,applicationId=p.applicationId??p.id??event.aggregate_id,status=p.status??p.decision;if((!email||!name)&&applicationId){const a=await client.query(`select email,phone,applicant_name,status from applications where id=$1`,[applicationId]);if(a.rowCount){email??=a.rows[0].email;phone??=a.rows[0].phone;name??=a.rows[0].applicant_name;status??=a.rows[0].status;}}
    if(event.topic==='admission.document_uploaded'){const admins=await client.query(`select id,email from users where role='ADMIN' and is_active=true`);return admins.rows.map(a=>({userId:a.id,email:a.email,title:'Dokumen pendaftaran baru',body:`Applicant mengunggah dokumen ${p.kind}.`,category:'admission_admin',actionUrl:`/admin/admissions/${applicationId}`,primary:[],dedupe:`admission-doc-admin:${p.documentId}:${a.id}`}));}
    if(event.topic==='admission.submitted'){const applicant:Target={email,phone,title:'Pendaftaran PMMI diterima',body:`Assalamu’alaikum ${name??''}. Form pendaftaranmu sudah kami terima dan akan diverifikasi.`,category:'admission',primary:['EMAIL','WHATSAPP'],fallback:{WHATSAPP:'EMAIL'},dedupe:`admission-submitted-applicant:${applicationId}`};const admins=await client.query(`select id,email from users where role='ADMIN' and is_active=true`);return [applicant,...admins.rows.map(a=>({userId:a.id,email:a.email,title:'Applicant baru',body:`Pendaftaran baru dari ${name??email}.`,category:'admission_admin',actionUrl:`/admin/admissions/${applicationId}`,primary:[],dedupe:`admission-new:${applicationId}:${a.id}`} as Target))];}
    const labels:Record<string,string>={ADMIN_VERIFIED:'Dokumen pendaftaran terverifikasi',SCREENING:'Pendaftaran masuk tahap seleksi',INTERVIEW:'Jadwal wawancara PMMI',ACCEPTED:'Selamat, kamu diterima di PMMI',WAITLISTED:'Status pendaftaran: waiting list',REJECTED:'Keputusan penerimaan PMMI',ENROLLED:'Registrasi PMMI selesai'};const title=event.topic==='admission.interview_scheduled'?'Jadwal wawancara PMMI':event.topic==='admission.decision'?(labels[String(status)]??'Keputusan penerimaan PMMI'):(labels[String(status)]??'Update pendaftaran PMMI');const body=event.topic==='admission.interview_scheduled'?`Wawancara dijadwalkan pada ${p.scheduledAt}. Lihat detail dari panitia PMMI.`:`Status pendaftaran ${name??''}: ${status}.`;return [{email,phone,title,body,category:'admission',primary:['EMAIL','WHATSAPP'],fallback:{WHATSAPP:'EMAIL'},dedupe:`${event.topic}:${applicationId}:${status??event.id}`,mandatory:['ACCEPTED','REJECTED'].includes(String(status))}];
  }
  if(event.topic==='class.session_changed'||event.topic==='class.session_reminder'){
    const classId=p.classId??p.class_id;const users=await classStudents(client,classId);const reminder=event.topic==='class.session_reminder';return users.map(u=>({userId:u.id,email:u.email,title:reminder?'Kelas segera dimulai':'Jadwal kelas diperbarui',body:reminder?`Kelas dimulai sekitar ${p.minutesBefore} menit lagi (${new Date(p.startsAt).toLocaleString('id-ID')}).`:`Jadwal kelas: ${new Date(p.starts_at).toLocaleString('id-ID')}.`,category:'schedule',primary:['WHATSAPP'],fallback:{WHATSAPP:'TELEGRAM'},dedupe:reminder?`class-reminder:${p.sessionId}:${u.id}`:`session:${p.id}:${p.updated_at??p.created_at}:${u.id}`}));
  }
  if(event.topic==='ai.credit_threshold'){const u=await userTarget(client,p.userId);return [{userId:p.userId,email:u.email,title:'AI credits menipis',body:`Sisa AI credits: ${p.balance}. Gunakan model dengan bijak atau hubungi admin bila membutuhkan tambahan.`,category:'ai',primary:[],dedupe:`ai-threshold:${p.userId}:${p.threshold}:${new Date().toISOString().slice(0,7)}`}];}
  if(event.topic==='digest.ustadz.daily'){return [{userId:p.userId,title:'Ringkasan tugas yang perlu dinilai',body:`Ada ${p.pending} submission yang menunggu penilaian/review.`,category:'digest',actionUrl:'/submissions',primary:[],dedupe:`ustadz-digest:${p.userId}:${p.day}`}];}
  if(event.topic==='student.lifecycle_changed'){
    const status=String(p.status);const student=await client.query(`select s.user_id,u.email,u.full_name from students s join users u on u.id=s.user_id where s.id=$1`,[p.id??event.aggregate_id]);if(!student.rowCount)return[];const s=student.rows[0];if(['DROPOUT','SUSPENDED','INACTIVE'].includes(status)){const admins=await client.query(`select id,email from users where role='ADMIN' and is_active=true`);return admins.rows.map(a=>({userId:a.id,email:a.email,title:'Review komunikasi lifecycle santri',body:`Status ${s.full_name} berubah menjadi ${status}. Komunikasi formal ke santri harus ditinjau admin sebelum dikirim.`,category:'lifecycle_admin',priority:'HIGH',actionUrl:'/admin/students',primary:[],dedupe:`lifecycle-review:${p.id}:${status}:${a.id}`,mandatory:true}));}if(['GRADUATED','ALUMNI'].includes(status))return [{userId:s.user_id,email:s.email,title:'Status PMMI diperbarui',body:status==='GRADUATED'?'Selamat atas kelulusanmu dari PMMI. Sertifikat dan arsip akademik tetap tersedia di dashboard.':'Akunmu kini berada pada mode alumni dengan akses akademik read-only.',category:'lifecycle',primary:['EMAIL','WHATSAPP'],fallback:{WHATSAPP:'TELEGRAM'},dedupe:`lifecycle:${p.id}:${status}`,mandatory:true}];
  }
  if(event.topic.startsWith('ops.')){const admins=await client.query(`select id,email from users where role='ADMIN' and is_active=true`);return admins.rows.map(a=>({userId:a.id,email:a.email,title:`PMMI Ops: ${p.title??event.topic}`,body:String(p.message??'Operational event requires attention.'),category:'ops',priority:'CRITICAL',primary:['TELEGRAM'],fallback:{TELEGRAM:'EMAIL'},dedupe:`ops:${event.id}:${a.id}`,mandatory:true}));}
  return[];
}

async function destination(client:pg.PoolClient,target:Target,channel:ExternalChannel){if(channel==='EMAIL'&&target.email)return target.email;if(channel==='WHATSAPP'&&target.phone)return target.phone;if(!target.userId)return null;const c=await client.query(`select address_or_external_id from user_notification_channels where user_id=$1 and channel=$2 and enabled=true and verified_at is not null order by priority,created_at limit 1`,[target.userId,channel]);if(c.rowCount)return c.rows[0].address_or_external_id as string;if(channel==='EMAIL'){const u=await client.query(`select email from users where id=$1`,[target.userId]);return u.rows[0]?.email??null;}return null;}
async function preferenceEnabled(client:pg.PoolClient,target:Target,channel:string){if(target.mandatory||channel==='IN_APP'||!target.userId)return true;const p=await client.query(`select enabled from notification_preferences where user_id=$1 and category=$2 and channel=$3`,[target.userId,target.category,channel]);return p.rowCount?Boolean(p.rows[0].enabled):true;}

export async function materializeNotifications(event:OutboxEvent){
  await workerTx(async client=>{const targets=await resolveTargets(client,event);for(const target of targets){const inserted=await client.query(`insert into notifications(user_id,type,category,title,body,recipient,priority,source_type,source_id,action_url,dedupe_key) values($1,$2,$3,$4,$5,$6::jsonb,$7,$8,$9,$10,$11) on conflict(user_id,dedupe_key) where dedupe_key is not null do nothing returning id`,[target.userId??null,event.topic,target.category,target.title,target.body,JSON.stringify({email:target.email??null,phone:target.phone??null}),target.priority??'NORMAL',event.aggregate_type,event.aggregate_id,target.actionUrl??null,target.dedupe]);if(!inserted.rowCount)continue;const notificationId=inserted.rows[0].id;if(target.userId)await client.query(`insert into notification_deliveries(notification_id,channel,status,sent_at) values($1,'IN_APP','SENT',now()) on conflict do nothing`,[notificationId]);for(const ch of target.primary){const enabled=await preferenceEnabled(client,target,ch);const to=await destination(client,target,ch);await client.query(`insert into notification_deliveries(notification_id,channel,status,last_error) values($1,$2,$3,$4) on conflict do nothing`,[notificationId,ch,enabled&&to?'PENDING':'SKIPPED',!enabled?'disabled by preference':!to?'channel not linked':null]);}for(const [forChannel,fallbackChannel] of Object.entries(target.fallback??{})){const ch=fallbackChannel as ExternalChannel;const enabled=await preferenceEnabled(client,target,ch);const to=await destination(client,target,ch);await client.query(`insert into notification_deliveries(notification_id,channel,status,last_error,is_fallback,fallback_for) values($1,$2,$3,$4,true,$5) on conflict do nothing`,[notificationId,ch,enabled&&to?'PENDING':'SKIPPED',!enabled?'disabled by preference':!to?'channel not linked':null,forChannel]);}}});
}

export async function processDeliveries(limit=30){
  const rows=await workerPool.query(`select d.id,d.notification_id,d.channel,d.attempt_count,d.fallback_for,n.user_id,n.title,n.body,n.recipient,n.category from notification_deliveries d join notifications n on n.id=d.notification_id where ((d.status in ('PENDING','FAILED')) or (d.status='SENDING' and d.updated_at<now()-interval '5 minutes')) and d.channel<>'IN_APP' and coalesce(d.next_attempt_at,now())<=now() and d.attempt_count<$1 and (d.is_fallback=false or exists(select 1 from notification_deliveries p where p.notification_id=d.notification_id and p.channel=d.fallback_for and (p.status='SKIPPED' or (p.status='FAILED' and p.attempt_count>=$1)))) order by n.priority desc,d.created_at limit $2`,[workerConfig.MAX_DELIVERY_ATTEMPTS,limit]);
  for(const d of rows.rows){await workerTx(async client=>{const lock=await client.query(`select status,attempt_count from notification_deliveries where id=$1 for update`,[d.id]);if(!lock.rowCount)return;const n=await client.query(`select user_id,title,body,recipient from notifications where id=$1`,[d.notification_id]);if(!n.rowCount)return;const notification=n.rows[0];let to:string|null=null;if(d.channel==='EMAIL')to=notification.recipient?.email??null;if(d.channel==='WHATSAPP')to=notification.recipient?.phone??null;if(!to&&notification.user_id){const c=await client.query(`select address_or_external_id from user_notification_channels where user_id=$1 and channel=$2 and enabled=true and verified_at is not null order by priority limit 1`,[notification.user_id,d.channel]);to=c.rows[0]?.address_or_external_id??null;if(!to&&d.channel==='EMAIL'){const u=await client.query(`select email from users where id=$1`,[notification.user_id]);to=u.rows[0]?.email??null;}}if(!to){await client.query(`update notification_deliveries set status='SKIPPED',last_error='channel not linked',updated_at=now() where id=$1`,[d.id]);return;}await client.query(`update notification_deliveries set status='SENDING',attempt_count=attempt_count+1,updated_at=now() where id=$1`,[d.id]);try{const sent=await sendExternal(d.channel as ExternalChannel,to,notification.title,notification.body);await client.query(`update notification_deliveries set status='SENT',provider_message_id=$1,sent_at=now(),last_error=null,updated_at=now() where id=$2`,[sent.providerMessageId,d.id]);await client.query(`update notification_deliveries set status='SKIPPED',last_error='another route succeeded',updated_at=now() where notification_id=$1 and is_fallback=true and status='PENDING'`,[d.notification_id]);}catch(error:any){const attempts=Number(lock.rows[0].attempt_count)+1;const unavailable=error instanceof ProviderUnavailable;const terminal=unavailable||attempts>=workerConfig.MAX_DELIVERY_ATTEMPTS;const backoff=Math.min(3600,Math.pow(2,attempts)*30);await client.query(`update notification_deliveries set status='FAILED',attempt_count=$1,last_error=$2,next_attempt_at=case when $3 then null else now()+($4||' seconds')::interval end,updated_at=now() where id=$5`,[terminal?workerConfig.MAX_DELIVERY_ATTEMPTS:attempts,String(error?.message??error).slice(0,1000),terminal,String(backoff),d.id]);}});}
}
