import Fastify from 'fastify';
import pg from 'pg';
import { Webhook } from 'svix';
const DATABASE_URL=process.env.DATABASE_URL;if(!DATABASE_URL)throw new Error('DATABASE_URL required');const SECRET=process.env.RESEND_WEBHOOK_SECRET;if(!SECRET)throw new Error('RESEND_WEBHOOK_SECRET required');const pool=new pg.Pool({connectionString:DATABASE_URL,max:3});const app=Fastify({logger:true});
app.addContentTypeParser('application/json',{parseAs:'string'},(_req,body,done)=>done(null,body));
app.get('/health',async()=>({status:'ok',service:'pmmi-webhooks'}));
app.post('/resend',async(req,reply)=>{const id=req.headers['svix-id'];const timestamp=req.headers['svix-timestamp'];const signature=req.headers['svix-signature'];if(typeof id!=='string'||typeof timestamp!=='string'||typeof signature!=='string')return reply.code(400).send({error:'missing Svix headers'});const raw=String(req.body??'');let event:any;try{event=new Webhook(SECRET).verify(raw,{'svix-id':id,'svix-timestamp':timestamp,'svix-signature':signature});}catch{return reply.code(401).send({error:'invalid webhook signature'});}const client=await pool.connect();try{await client.query('begin');const stored=await client.query(`insert into notification_webhook_events(provider,event_id,event_type,payload) values('RESEND',$1,$2,$3::jsonb) on conflict(provider,event_id) do nothing returning event_id`,[id,String(event?.type??''),JSON.stringify(event)]);const emailId=event?.data?.email_id?String(event.data.email_id):null;if(stored.rowCount&&emailId){const type=String(event.type);if(type==='email.delivered')await client.query(`update notification_deliveries set status='DELIVERED',delivered_at=coalesce(delivered_at,now()),updated_at=now() where channel='EMAIL' and provider_message_id=$1`,[emailId]);else if(type==='email.sent')await client.query(`update notification_deliveries set status=case when status='PENDING' then 'SENT' else status end,sent_at=coalesce(sent_at,now()),updated_at=now() where channel='EMAIL' and provider_message_id=$1`,[emailId]);else if(['email.failed','email.bounced','email.suppressed'].includes(type))await client.query(`update notification_deliveries set status='FAILED',last_error=$2,updated_at=now() where channel='EMAIL' and provider_message_id=$1`,[emailId,JSON.stringify(event?.data??{}).slice(0,2000)]);else if(type==='email.delivery_delayed')await client.query(`update notification_deliveries set last_error='Resend delivery delayed',updated_at=now() where channel='EMAIL' and provider_message_id=$1`,[emailId]);}await client.query('commit');return{ok:true};}catch(e){await client.query('rollback');throw e}finally{client.release()}});
const port=Number(process.env.PORT??3011);await app.listen({port,host:process.env.HOST??'0.0.0.0'});
for(const sig of ['SIGINT','SIGTERM'] as const)process.on(sig,async()=>{await app.close();await pool.end();process.exit(0)});
