import { createHash,randomBytes,randomUUID } from 'node:crypto';
import type { FastifyInstance,FastifyReply,FastifyRequest } from 'fastify';
import { z } from 'zod';
import { pool,withTransaction } from '../db.js';
import { requireAuth,type SessionUser } from '../security/authz.js';
import { writeAudit } from '../audit.js';

const keyHash=(v:string)=>createHash('sha256').update(v).digest('hex');
const routerBase=()=>String(process.env.NINEROUTER_BASE_URL??'http://127.0.0.1:20128').replace(/\/$/,'');
const routerKey=()=>process.env.NINEROUTER_API_KEY;
const requestsPerMinute=()=>Math.max(1,Number(process.env.AI_REQUESTS_PER_MINUTE??20));
const workspaceBase=()=>String(process.env.HERMES_WORKSPACE_BASE??'/srv/pmmi/workspaces').replace(/\/$/,'');

async function aiSession(request:FastifyRequest,reply:FastifyReply):Promise<SessionUser|null>{
  const auth=request.headers.authorization;
  if(auth?.startsWith('Bearer pmmi_')){const raw=auth.slice(7);const r=await pool.query(`select k.id,k.user_id,u.role,u.is_active from ai_api_keys k join users u on u.id=k.user_id where k.key_hash=$1 and k.revoked_at is null and (k.expires_at is null or k.expires_at>now())`,[keyHash(raw)]);if(!r.rowCount||!r.rows[0].is_active){reply.code(401).send({error:'invalid AI API key'});return null;}await pool.query(`update ai_api_keys set last_used_at=now() where id=$1`,[r.rows[0].id]);return{sub:r.rows[0].user_id,role:r.rows[0].role};}
  return requireAuth(request,reply);
}
async function modelAllowed(session:SessionUser,model:string){const r=await pool.query(`select enabled,model_pattern from ai_model_policies where role=$1 order by length(model_pattern) desc`,[session.role]);if(!r.rowCount)return true;const matches=r.rows.filter(x=>model.startsWith(String(x.model_pattern).replace(/\*$/,'')));return matches.length?matches[0].enabled:false;}
async function checkRate(userId:string){const r=await pool.query(`select count(*)::int count from ai_usage_logs where user_id=$1 and created_at>now()-interval '1 minute'`,[userId]);return r.rows[0].count<requestsPerMinute();}
async function reserve(userId:string,amount:number,requestId:string,model:string){return withTransaction(async client=>{await client.query(`insert into ai_credit_wallets(user_id,balance) values($1,0) on conflict(user_id) do nothing`,[userId]);const w=await client.query(`select balance from ai_credit_wallets where user_id=$1 for update`,[userId]);const before=Number(w.rows[0].balance);if(before<amount)return null;const after=before-amount;await client.query(`update ai_credit_wallets set balance=$1,updated_at=now() where user_id=$2`,[after,userId]);await client.query(`insert into ai_credit_ledger(user_id,delta,balance_after,reason,source_type,source_id,idempotency_key) values($1,$2,$3,'ai.reserve','ai_request',$4,$5)`,[userId,-amount,after,requestId,`reserve:${requestId}`]);await client.query(`insert into ai_usage_logs(user_id,request_id,model,reserved_credits,status) values($1,$2,$3,$4,'RESERVED')`,[userId,requestId,model,amount]);return{before,after};});}
async function reconcile(userId:string,requestId:string,reserved:number,usage:any,status:'SUCCEEDED'|'FAILED',error?:string){const total=Number(usage?.total_tokens??0);const charged=status==='SUCCEEDED'?Math.max(1,Math.ceil(total/1000)):0;const refund=Math.max(0,reserved-charged);await withTransaction(async client=>{const w=await client.query(`select balance from ai_credit_wallets where user_id=$1 for update`,[userId]);let balance=Number(w.rows[0]?.balance??0);if(refund){balance+=refund;await client.query(`update ai_credit_wallets set balance=$1,updated_at=now() where user_id=$2`,[balance,userId]);await client.query(`insert into ai_credit_ledger(user_id,delta,balance_after,reason,source_type,source_id,idempotency_key) values($1,$2,$3,'ai.reconcile','ai_request',$4,$5)`,[userId,refund,balance,requestId,`reconcile:${requestId}`]);}await client.query(`update ai_usage_logs set input_tokens=$2,output_tokens=$3,total_tokens=$4,charged_credits=$5,status=$6,error=$7,completed_at=now() where request_id=$1`,[requestId,usage?.prompt_tokens??null,usage?.completion_tokens??null,total||null,charged,status,error??null]);if(status==='SUCCEEDED'&&balance<=5)await client.query(`insert into notification_outbox(event_type,source_type,source_id,payload,dedupe_key) values('ai.credit_low','ai_wallet',$1,jsonb_build_object('userId',$1::uuid,'balance',$2::bigint),$3) on conflict do nothing`,[userId,balance,`ai-low:${userId}:${balance}`]);});return charged;}

export async function registerBlueprintAIHermesRoutes(app:FastifyInstance){
  const models=async(request:FastifyRequest,reply:FastifyReply)=>{const session=await aiSession(request,reply);if(!session)return;const headers:Record<string,string>={};if(routerKey())headers.authorization=`Bearer ${routerKey()}`;const r=await fetch(`${routerBase()}/v1/models`,{headers});const d=await r.text();reply.code(r.status).header('content-type',r.headers.get('content-type')??'application/json').send(d);};
  app.get('/v1/ai/models',models);app.get('/v1/models',models);
  const chat=async(request:FastifyRequest,reply:FastifyReply)=>{const session=await aiSession(request,reply);if(!session)return;const p=z.object({model:z.string().min(1),messages:z.array(z.object({role:z.string(),content:z.any()})).min(1),stream:z.boolean().default(false),max_tokens:z.number().int().positive().max(32768).optional()}).passthrough().safeParse(request.body);if(!p.success)return reply.code(400).send({error:'invalid OpenAI-compatible payload'});if(p.data.stream)return reply.code(400).send({error:'streaming is disabled so PMMI can reconcile credits deterministically'});if(!await modelAllowed(session,p.data.model))return reply.code(403).send({error:'model is not allowed for this role'});if(!await checkRate(session.sub))return reply.code(429).send({error:'AI rate limit exceeded'});const requestId=randomUUID();const reserved=Math.max(1,Math.ceil(Number(p.data.max_tokens??2048)/1000));const held=await reserve(session.sub,reserved,requestId,p.data.model);if(!held)return reply.code(402).send({error:'insufficient AI credits'});try{const headers:Record<string,string>={'content-type':'application/json'};if(routerKey())headers.authorization=`Bearer ${routerKey()}`;const r=await fetch(`${routerBase()}/v1/chat/completions`,{method:'POST',headers,body:JSON.stringify({...request.body,stream:false})});const text=await r.text();let d:any;try{d=JSON.parse(text)}catch{d={error:text}};if(!r.ok){await reconcile(session.sub,requestId,reserved,null,'FAILED',`9Router ${r.status}`);return reply.code(r.status).send(d);}const charged=await reconcile(session.sub,requestId,reserved,d.usage,'SUCCEEDED');reply.header('x-pmmi-request-id',requestId).header('x-pmmi-credits-charged',String(charged));return d;}catch(e:any){await reconcile(session.sub,requestId,reserved,null,'FAILED',e?.message??String(e));return reply.code(502).send({error:'AI upstream unavailable'});}};
  app.post('/v1/ai/chat/completions',chat);app.post('/v1/chat/completions',chat);
  app.get('/v1/ai/wallet',async(request,reply)=>{const session=await requireAuth(request,reply);if(!session)return;const w=await pool.query(`select balance,updated_at from ai_credit_wallets where user_id=$1`,[session.sub]);const month=await pool.query(`select coalesce(sum(case when delta<0 then -delta else 0 end),0)::bigint spent,coalesce(sum(case when delta>0 then delta else 0 end),0)::bigint granted from ai_credit_ledger where user_id=$1 and created_at>=date_trunc('month',now())`,[session.sub]);return{balance:Number(w.rows[0]?.balance??0),updatedAt:w.rows[0]?.updated_at??null,month:month.rows[0]};});
  app.get('/v1/ai/ledger',async(request,reply)=>{const session=await requireAuth(request,reply);if(!session)return;const r=await pool.query(`select * from ai_credit_ledger where user_id=$1 order by created_at desc limit 200`,[session.sub]);return{items:r.rows};});
  app.post('/v1/admin/ai/credits/grant',async(request,reply)=>{const session=await requireAuth(request,reply,['ADMIN']);if(!session)return;const p=z.object({userId:z.string().uuid(),amount:z.number().int().positive(),reason:z.string().min(2)}).safeParse(request.body);if(!p.success)return reply.code(400).send({error:'invalid payload'});const result=await withTransaction(async client=>{await client.query(`insert into ai_credit_wallets(user_id,balance) values($1,0) on conflict do nothing`,[p.data.userId]);const w=await client.query(`select balance from ai_credit_wallets where user_id=$1 for update`,[p.data.userId]);const after=Number(w.rows[0].balance)+p.data.amount;await client.query(`update ai_credit_wallets set balance=$1,updated_at=now() where user_id=$2`,[after,p.data.userId]);await client.query(`insert into ai_credit_ledger(user_id,delta,balance_after,reason,source_type,source_id,idempotency_key) values($1,$2,$3,$4,'admin',$5,$6)`,[p.data.userId,p.data.amount,after,p.data.reason,session.sub,`admin:${session.sub}:${randomUUID()}`]);await writeAudit(client,session.sub,'ai.credits_granted','user',p.data.userId,{amount:p.data.amount,reason:p.data.reason});return{balance:after};});return result;});
  app.post('/v1/ai/api-keys',async(request,reply)=>{const session=await requireAuth(request,reply);if(!session)return;const p=z.object({label:z.string().min(2).max(100),expiresAt:z.string().datetime().optional()}).safeParse(request.body);if(!p.success)return reply.code(400).send({error:'invalid payload'});const raw=`pmmi_${randomBytes(32).toString('base64url')}`;const r=await pool.query(`insert into ai_api_keys(user_id,key_hash,key_prefix,label,expires_at) values($1,$2,$3,$4,$5) returning id,key_prefix,label,created_at`,[session.sub,keyHash(raw),raw.slice(0,14),p.data.label,p.data.expiresAt??null]);return reply.code(201).send({...r.rows[0],apiKey:raw});});
  app.delete('/v1/ai/api-keys/:id',async(request,reply)=>{const session=await requireAuth(request,reply);if(!session)return;const{id}=request.params as{id:string};const r=await pool.query(`update ai_api_keys set revoked_at=now() where id=$1 and user_id=$2 and revoked_at is null returning id`,[id,session.sub]);if(!r.rowCount)return reply.code(404).send({error:'key not found'});return{revoked:true};});
  app.put('/v1/admin/ai/model-policies',async(request,reply)=>{const session=await requireAuth(request,reply,['ADMIN']);if(!session)return;const p=z.object({role:z.enum(['ADMIN','USTADZ','SANTRI']),modelPattern:z.string().min(1),enabled:z.boolean()}).safeParse(request.body);if(!p.success)return reply.code(400).send({error:'invalid payload'});const r=await pool.query(`insert into ai_model_policies(role,model_pattern,enabled) values($1,$2,$3) on conflict(role,model_pattern) do update set enabled=excluded.enabled returning *`,[p.data.role,p.data.modelPattern,p.data.enabled]);return r.rows[0];});

  app.get('/v1/hermes/profiles',async(request,reply)=>{const session=await requireAuth(request,reply);if(!session)return;const r=await pool.query(`select p.*,w.workspace_path,w.quota_bytes,w.archived_at from hermes_profiles p left join hermes_workspaces w on w.hermes_profile_id=p.id where p.user_id=$1 order by p.created_at desc`,[session.sub]);const e=await pool.query(`select hermes_agent_slots,storage_quota_bytes from resource_entitlements where user_id=$1`,[session.sub]);return{items:r.rows,entitlement:{slots:Number(e.rows[0]?.hermes_agent_slots??0),storageQuotaBytes:Number(e.rows[0]?.storage_quota_bytes??0)}};});
  app.post('/v1/hermes/build',async(request,reply)=>{const session=await requireAuth(request,reply);if(!session)return;const p=z.object({name:z.string().min(2).max(40).regex(/^[a-zA-Z0-9_-]+$/),role:z.string().max(40).default('general'),description:z.string().max(1000).optional()}).safeParse(request.body);if(!p.success)return reply.code(400).send({error:'invalid payload'});if(session.role==='SANTRI'){const s=await pool.query(`select status from students where user_id=$1`,[session.sub]);if(!s.rowCount||s.rows[0].status!=='ACTIVE')return reply.code(403).send({error:'only active santri can build agents'});}const e=await pool.query(`select hermes_agent_slots,storage_quota_bytes from resource_entitlements where user_id=$1`,[session.sub]);const slots=Number(e.rows[0]?.hermes_agent_slots??0);const active=await pool.query(`select count(*)::int count from hermes_profiles where user_id=$1 and status not in('ARCHIVED','FAILED')`,[session.sub]);if(active.rows[0].count>=slots)return reply.code(409).send({error:'no Hermes agent slot available'});const result=await withTransaction(async client=>{const profileName=`${session.role.toLowerCase()}-${session.sub.slice(0,8)}-${p.data.name}`;const pr=await client.query(`insert into hermes_profiles(user_id,profile_name,role,description) values($1,$2,$3,$4) returning *`,[session.sub,profileName,p.data.role,p.data.description??null]);const path=`${workspaceBase()}/${session.sub}/${pr.rows[0].id}`;await client.query(`insert into hermes_workspaces(hermes_profile_id,workspace_path,quota_bytes) values($1,$2,$3)`,[pr.rows[0].id,path,Number(e.rows[0]?.storage_quota_bytes??0)]);const j=await client.query(`insert into hermes_build_jobs(hermes_profile_id,job_type) values($1,'BUILD') returning *`,[pr.rows[0].id]);return{profile:pr.rows[0],workspacePath:path,job:j.rows[0]};});return reply.code(202).send(result);});
  app.post('/v1/hermes/profiles/:id/action',async(request,reply)=>{const session=await requireAuth(request,reply);if(!session)return;const{id}=request.params as{id:string};const p=z.object({action:z.enum(['START','STOP','ARCHIVE'])}).safeParse(request.body);if(!p.success)return reply.code(400).send({error:'invalid action'});const own=await pool.query(`select id from hermes_profiles where id=$1 and user_id=$2`,[id,session.sub]);if(!own.rowCount)return reply.code(404).send({error:'profile not found'});const j=await pool.query(`insert into hermes_build_jobs(hermes_profile_id,job_type) values($1,$2) returning *`,[id,p.data.action]);return reply.code(202).send(j.rows[0]);});

  app.post('/v1/admin/rewards',async(request,reply)=>{const session=await requireAuth(request,reply,['ADMIN']);if(!session)return;const p=z.object({code:z.string().min(2),name:z.string().min(2),description:z.string().optional(),aiCredits:z.number().int().nonnegative().default(0),agentSlots:z.number().int().nonnegative().default(0),badge:z.string().optional()}).safeParse(request.body);if(!p.success)return reply.code(400).send({error:'invalid payload'});const d=p.data;const r=await pool.query(`insert into rewards(code,name,description,ai_credits,agent_slots,badge) values(upper($1),$2,$3,$4,$5,$6) returning *`,[d.code,d.name,d.description??null,d.aiCredits,d.agentSlots,d.badge??null]);return reply.code(201).send(r.rows[0]);});
  app.post('/v1/admin/reward-rules',async(request,reply)=>{const session=await requireAuth(request,reply,['ADMIN']);if(!session)return;const p=z.object({rewardId:z.string().uuid(),eventType:z.string().min(2),criteria:z.record(z.unknown()).default({})}).safeParse(request.body);if(!p.success)return reply.code(400).send({error:'invalid payload'});const r=await pool.query(`insert into reward_rules(reward_id,event_type,criteria) values($1,$2,$3::jsonb) returning *`,[p.data.rewardId,p.data.eventType,JSON.stringify(p.data.criteria)]);return reply.code(201).send(r.rows[0]);});
  app.get('/v1/rewards/achievements',async(request,reply)=>{const session=await requireAuth(request,reply);if(!session)return;const r=await pool.query(`select a.*,r.code,r.name,r.description,r.ai_credits,r.agent_slots,r.badge from achievements a join rewards r on r.id=a.reward_id where a.user_id=$1 order by a.earned_at desc`,[session.sub]);return{items:r.rows};});
  app.post('/v1/admin/rewards/evaluate-grade/:submissionId',async(request,reply)=>{const session=await requireAuth(request,reply,['ADMIN']);if(!session)return;const{submissionId}=request.params as{submissionId:string};const grade=await pool.query(`select s.student_user_id,g.score,co.code course_code from submissions s join grades g on g.submission_id=s.id join assignments a on a.id=s.assignment_id join classes c on c.id=a.class_id join courses co on co.id=c.course_id where s.id=$1 and g.score is not null`,[submissionId]);if(!grade.rowCount)return reply.code(404).send({error:'graded submission not found'});const g=grade.rows[0];const rules=await pool.query(`select rr.id rule_id,rr.reward_id,rr.criteria,r.ai_credits,r.agent_slots from reward_rules rr join rewards r on r.id=rr.reward_id where rr.event_type='submission.graded' and rr.is_active=true and r.is_active=true`);const granted=[] as string[];for(const rule of rules.rows){const c=rule.criteria??{};if(Number(g.score)<Number(c.minScore??0)||(c.courseCode&&c.courseCode!==g.course_code))continue;try{const achievement=await withTransaction(async client=>{const a=await client.query(`insert into achievements(user_id,reward_rule_id,reward_id,source_type,source_id,metadata) values($1,$2,$3,'submission',$4,$5::jsonb) returning id`,[g.student_user_id,rule.rule_id,rule.reward_id,submissionId,JSON.stringify({score:Number(g.score),courseCode:g.course_code})]);const credits=Number(rule.ai_credits);if(credits>0){await client.query(`insert into ai_credit_wallets(user_id,balance) values($1,0) on conflict do nothing`,[g.student_user_id]);const w=await client.query(`select balance from ai_credit_wallets where user_id=$1 for update`,[g.student_user_id]);const after=Number(w.rows[0].balance)+credits;await client.query(`update ai_credit_wallets set balance=$1,updated_at=now() where user_id=$2`,[after,g.student_user_id]);await client.query(`insert into ai_credit_ledger(user_id,delta,balance_after,reason,source_type,source_id,idempotency_key) values($1,$2,$3,'reward','achievement',$4,$5)`,[g.student_user_id,credits,after,a.rows[0].id,`reward:${a.rows[0].id}`]);}if(Number(rule.agent_slots)>0)await client.query(`update resource_entitlements set hermes_agent_slots=hermes_agent_slots+$2,updated_at=now() where user_id=$1`,[g.student_user_id,Number(rule.agent_slots)]);return a.rows[0].id;});granted.push(achievement);}catch(e:any){if(e?.code!=='23505')throw e;}}return{granted};});
}
