import type { FastifyInstance } from 'fastify';
import { z } from 'zod';
import { pool,withTransaction } from '../db.js';
import { requireAuth } from '../security/authz.js';
import { minio } from '../storage.js';
import { writeAudit } from '../audit.js';

const routerBase=()=>String(process.env.NINEROUTER_BASE_URL??'http://127.0.0.1:20128').replace(/\/$/,'');

export async function registerBlueprintOpsRoutes(app:FastifyInstance){
  app.get('/v1/dashboard/summary',async(request,reply)=>{const session=await requireAuth(request,reply);if(!session)return;if(session.role==='ADMIN'){const [students,teachers,apps,pending,usage,hermes]=await Promise.all([pool.query(`select count(*)::int count from students where status='ACTIVE'`),pool.query(`select count(*)::int count from users where role='USTADZ' and is_active=true`),pool.query(`select count(*)::int count from applications`),pool.query(`select count(*)::int count from submissions where status in('submitted','resubmitted')`),pool.query(`select count(*)::int requests,coalesce(sum(charged_credits),0)::bigint credits from ai_usage_logs where created_at>=date_trunc('month',now())`),pool.query(`select count(*)::int count from hermes_profiles where status not in('ARCHIVED','FAILED')`)]);return{role:'ADMIN',activeStudents:students.rows[0].count,activeTeachers:teachers.rows[0].count,applications:apps.rows[0].count,pendingGrading:pending.rows[0].count,aiMonth:usage.rows[0],activeHermes:hermes.rows[0].count};}if(session.role==='USTADZ'){const [classes,pending,sessions]=await Promise.all([pool.query(`select count(*)::int count from classes where teacher_user_id=$1`,[session.sub]),pool.query(`select count(*)::int count from submissions s join assignments a on a.id=s.assignment_id join classes c on c.id=a.class_id where c.teacher_user_id=$1 and s.status in('submitted','resubmitted')`,[session.sub]),pool.query(`select count(*)::int count from class_sessions cs join classes c on c.id=cs.class_id where c.teacher_user_id=$1 and cs.starts_at>=now()`,[session.sub])]);return{role:'USTADZ',classes:classes.rows[0].count,pendingGrading:pending.rows[0].count,upcomingSessions:sessions.rows[0].count};}const [assignments,grades,certs,wallet,agents]=await Promise.all([pool.query(`select count(*)::int count from assignments a join enrollments e on e.class_id=a.class_id where e.student_user_id=$1 and e.status='active'`,[session.sub]),pool.query(`select count(*)::int count from grades g join submissions s on s.id=g.submission_id where s.student_user_id=$1`,[session.sub]),pool.query(`select count(*)::int count from certificates where student_user_id=$1`,[session.sub]),pool.query(`select balance from ai_credit_wallets where user_id=$1`,[session.sub]),pool.query(`select count(*)::int count from hermes_profiles where user_id=$1 and status not in('ARCHIVED','FAILED')`,[session.sub])]);return{role:'SANTRI',assignments:assignments.rows[0].count,graded:grades.rows[0].count,certificates:certs.rows[0].count,aiCredits:Number(wallet.rows[0]?.balance??0),agents:agents.rows[0].count};});

  app.get('/v1/admin/ops/status',async(request,reply)=>{const session=await requireAuth(request,reply,['ADMIN']);if(!session)return;const status:any={database:{status:'UNKNOWN'},minio:{status:'UNKNOWN'},nineRouter:{status:'UNKNOWN'},workers:[],providers:[],backups:[]};try{await pool.query('select 1');status.database={status:'OK'};}catch(e:any){status.database={status:'ERROR',error:e.message};}try{await minio.listBuckets();status.minio={status:'OK'};}catch(e:any){status.minio={status:'ERROR',error:e.message};}try{const headers:Record<string,string>={};if(process.env.NINEROUTER_API_KEY)headers.authorization=`Bearer ${process.env.NINEROUTER_API_KEY}`;const r=await fetch(`${routerBase()}/v1/models`,{headers,signal:AbortSignal.timeout(3000)});status.nineRouter={status:r.ok?'OK':'ERROR',httpStatus:r.status};}catch(e:any){status.nineRouter={status:'ERROR',error:e.message};}status.workers=(await pool.query(`select service,instance_id,metadata,last_seen_at,case when last_seen_at>now()-interval '2 minutes' then 'OK' else 'STALE' end status from service_heartbeats order by service`)).rows;status.providers=(await pool.query(`select * from notification_provider_health order by channel`)).rows;status.backups=(await pool.query(`select * from backup_runs order by started_at desc limit 10`)).rows;return status;});
  app.get('/v1/admin/ops/audit',async(request,reply)=>{const session=await requireAuth(request,reply,['ADMIN']);if(!session)return;const r=await pool.query(`select a.*,u.email actor_email from audit_logs a left join users u on u.id=a.actor_user_id order by a.created_at desc limit 500`);return{items:r.rows};});
  app.get('/v1/admin/ops/health-events',async(request,reply)=>{const session=await requireAuth(request,reply,['ADMIN']);if(!session)return;const r=await pool.query(`select * from system_health_events order by created_at desc limit 200`);return{items:r.rows};});
  app.post('/v1/admin/ops/health-events',async(request,reply)=>{const session=await requireAuth(request,reply,['ADMIN']);if(!session)return;const p=z.object({service:z.string().min(1),severity:z.enum(['INFO','WARNING','CRITICAL']),eventType:z.string().min(1),message:z.string().min(1),metadata:z.record(z.unknown()).default({})}).safeParse(request.body);if(!p.success)return reply.code(400).send({error:'invalid payload'});const r=await pool.query(`insert into system_health_events(service,severity,event_type,message,metadata) values($1,$2,$3,$4,$5::jsonb) returning *`,[p.data.service,p.data.severity,p.data.eventType,p.data.message,JSON.stringify(p.data.metadata)]);if(p.data.severity==='CRITICAL')await pool.query(`insert into notification_outbox(event_type,source_type,source_id,payload,dedupe_key) values('ops.alert','health_event',$1,jsonb_build_object('title',$2::text,'body',$3::text),$4) on conflict do nothing`,[String(r.rows[0].id),`${p.data.service}: ${p.data.eventType}`,p.data.message,`health:${r.rows[0].id}`]);return reply.code(201).send(r.rows[0]);});

  app.get('/v1/admin/communications',async(request,reply)=>{const session=await requireAuth(request,reply,['ADMIN']);if(!session)return;const q=request.query as{status?:string};const r=await pool.query(`select pc.*,u.email,u.full_name from pending_communications pc join users u on u.id=pc.user_id where ($1::text='ALL' or pc.status=$1) order by pc.created_at desc limit 200`,[q.status??'DRAFT']);return{items:r.rows};});
  app.post('/v1/admin/communications/:id/review',async(request,reply)=>{const session=await requireAuth(request,reply,['ADMIN']);if(!session)return;const{id}=request.params as{id:string};const p=z.object({action:z.enum(['APPROVE','CANCEL']),title:z.string().min(2).max(200).optional(),body:z.string().min(2).max(5000).optional(),channels:z.array(z.enum(['IN_APP','EMAIL','WHATSAPP','TELEGRAM'])).min(1).optional()}).safeParse(request.body);if(!p.success)return reply.code(400).send({error:'invalid payload'});const result=await withTransaction(async client=>{const current=await client.query(`select * from pending_communications where id=$1 for update`,[id]);if(!current.rowCount)return{kind:'notfound' as const};if(current.rows[0].status!=='DRAFT')return{kind:'final' as const,status:current.rows[0].status};if(p.data.action==='CANCEL'){await client.query(`update pending_communications set status='CANCELLED',reviewed_by=$2,reviewed_at=now() where id=$1`,[id,session.sub]);await writeAudit(client,session.sub,'communication.cancelled','pending_communication',id);return{kind:'cancelled' as const};}const title=p.data.title??current.rows[0].title;const body=p.data.body??current.rows[0].body;const channels=p.data.channels??current.rows[0].proposed_channels;await client.query(`update pending_communications set status='APPROVED',title=$2,body=$3,proposed_channels=$4::jsonb,reviewed_by=$5,reviewed_at=now() where id=$1`,[id,title,body,JSON.stringify(channels),session.sub]);await client.query(`insert into notification_outbox(event_type,source_type,source_id,payload,dedupe_key) values('student.lifecycle_approved',$1,$2,jsonb_build_object('userId',$3::uuid,'title',$4::text,'body',$5::text,'channels',$6::jsonb),$7)`,[current.rows[0].source_type,current.rows[0].source_id,current.rows[0].user_id,title,body,JSON.stringify(channels),`communication:${id}`]);await writeAudit(client,session.sub,'communication.approved','pending_communication',id,{channels});return{kind:'approved' as const};});if(result.kind==='notfound')return reply.code(404).send({error:'communication not found'});if(result.kind==='final')return reply.code(409).send({error:`communication already ${result.status}`});return result;});
}
