import { createHash,randomBytes } from 'node:crypto';
import type { FastifyInstance } from 'fastify';
import { z } from 'zod';
import { pool } from '../db.js';
import { requireAuth } from '../security/authz.js';

const hash=(v:string)=>createHash('sha256').update(v).digest('hex');
const telegramToken=()=>process.env.TELEGRAM_BOT_TOKEN;
const telegramUser=()=>process.env.TELEGRAM_BOT_USERNAME;
const telegramSecret=()=>process.env.TELEGRAM_WEBHOOK_SECRET;

export async function registerBlueprintNotificationRoutes(app:FastifyInstance){
  app.get('/v1/notifications',async(request,reply)=>{const session=await requireAuth(request,reply);if(!session)return;const q=request.query as{unreadOnly?:string;limit?:string};const limit=Math.min(Math.max(Number(q.limit??50),1),100);const r=await pool.query(`select id,type,category,title,body,data,priority,action_url,read_at,created_at from notifications where user_id=$1 and ($2::boolean=false or read_at is null) order by created_at desc limit $3`,[session.sub,q.unreadOnly==='true',limit]);const unread=await pool.query(`select count(*)::int count from notifications where user_id=$1 and read_at is null`,[session.sub]);return{items:r.rows,unread:unread.rows[0].count};});
  app.patch('/v1/notifications/:id/read',async(request,reply)=>{const session=await requireAuth(request,reply);if(!session)return;const{id}=request.params as{id:string};const r=await pool.query(`update notifications set read_at=coalesce(read_at,now()) where id=$1 and user_id=$2 returning id,read_at`,[id,session.sub]);if(!r.rowCount)return reply.code(404).send({error:'notification not found'});return r.rows[0];});
  app.post('/v1/notifications/read-all',async(request,reply)=>{const session=await requireAuth(request,reply);if(!session)return;const r=await pool.query(`update notifications set read_at=now() where user_id=$1 and read_at is null`,[session.sub]);return{updated:r.rowCount??0};});
  app.get('/v1/notifications/channels',async(request,reply)=>{const session=await requireAuth(request,reply);if(!session)return;const r=await pool.query(`select id,channel,address_or_external_id,verified_at,enabled,priority,metadata,created_at from user_notification_channels where user_id=$1 order by priority,created_at`,[session.sub]);return{items:r.rows};});
  app.post('/v1/notifications/channels',async(request,reply)=>{const session=await requireAuth(request,reply);if(!session)return;const p=z.object({channel:z.enum(['EMAIL','WHATSAPP']),address:z.string().min(3).max(320),enabled:z.boolean().default(true),priority:z.number().int().min(1).max(1000).default(100)}).safeParse(request.body);if(!p.success)return reply.code(400).send({error:'invalid payload'});const d=p.data;const address=d.channel==='EMAIL'?d.address.trim().toLowerCase():d.address.replace(/\D/g,'');if(d.channel==='WHATSAPP'&&address.length<8)return reply.code(400).send({error:'invalid WhatsApp number'});const r=await pool.query(`insert into user_notification_channels(user_id,channel,address_or_external_id,verified_at,enabled,priority) values($1,$2,$3,case when $2='EMAIL' and lower($3)=(select lower(email) from users where id=$1) then now() else null end,$4,$5) on conflict(user_id,channel,address_or_external_id) do update set enabled=excluded.enabled,priority=excluded.priority,updated_at=now() returning *`,[session.sub,d.channel,address,d.enabled,d.priority]);return reply.code(201).send(r.rows[0]);});
  app.delete('/v1/notifications/channels/:id',async(request,reply)=>{const session=await requireAuth(request,reply);if(!session)return;const{id}=request.params as{id:string};const r=await pool.query(`update user_notification_channels set enabled=false,updated_at=now() where id=$1 and user_id=$2 returning id`,[id,session.sub]);if(!r.rowCount)return reply.code(404).send({error:'channel not found'});return{disabled:true};});
  app.get('/v1/notifications/preferences',async(request,reply)=>{const session=await requireAuth(request,reply);if(!session)return;const r=await pool.query(`select category,channel,enabled,digest,quiet_hours from notification_preferences where user_id=$1 order by category,channel`,[session.sub]);return{items:r.rows};});
  app.put('/v1/notifications/preferences',async(request,reply)=>{const session=await requireAuth(request,reply);if(!session)return;const p=z.object({category:z.string().min(1).max(80),channel:z.enum(['IN_APP','EMAIL','WHATSAPP','TELEGRAM']),enabled:z.boolean(),digest:z.boolean().default(false)}).safeParse(request.body);if(!p.success)return reply.code(400).send({error:'invalid payload'});const d=p.data;const r=await pool.query(`insert into notification_preferences(user_id,category,channel,enabled,digest) values($1,$2,$3,$4,$5) on conflict(user_id,category,channel) do update set enabled=excluded.enabled,digest=excluded.digest returning category,channel,enabled,digest`,[session.sub,d.category,d.channel,d.enabled,d.digest]);return r.rows[0];});
  app.post('/v1/notifications/telegram/link-token',async(request,reply)=>{const session=await requireAuth(request,reply);if(!session)return;if(!telegramToken()||!telegramUser())return reply.code(503).send({error:'Telegram is not configured'});const token=randomBytes(24).toString('base64url');await pool.query(`insert into telegram_link_tokens(user_id,token_hash,expires_at) values($1,$2,now()+interval '15 minutes')`,[session.sub,hash(token)]);return{token,expiresInSeconds:900,deepLink:`https://t.me/${telegramUser()}?start=${token}`};});
  app.post('/v1/notifications/telegram/webhook',async(request,reply)=>{if(!telegramSecret()||request.headers['x-telegram-bot-api-secret-token']!==telegramSecret())return reply.code(401).send({error:'invalid webhook secret'});const update=request.body as any;const text=update?.message?.text as string|undefined;const chatId=update?.message?.chat?.id;if(!text?.startsWith('/start ')||chatId==null)return{ok:true};const r=await pool.query(`update telegram_link_tokens set used_at=now() where token_hash=$1 and used_at is null and expires_at>now() returning user_id`,[hash(text.slice(7).trim())]);if(!r.rowCount)return reply.code(400).send({error:'invalid or expired link token'});await pool.query(`insert into user_notification_channels(user_id,channel,address_or_external_id,verified_at,enabled,priority,metadata) values($1,'TELEGRAM',$2,now(),true,80,$3::jsonb) on conflict(user_id,channel,address_or_external_id) do update set verified_at=now(),enabled=true,updated_at=now(),metadata=excluded.metadata`,[r.rows[0].user_id,String(chatId),JSON.stringify({username:update?.message?.from?.username??null})]);return{ok:true};});
  app.get('/v1/admin/notifications/deliveries',async(request,reply)=>{const session=await requireAuth(request,reply,['ADMIN']);if(!session)return;const r=await pool.query(`select d.*,n.type,n.title,n.user_id from notification_deliveries d join notifications n on n.id=d.notification_id order by d.created_at desc limit 200`);return{items:r.rows};});
}
