import type { FastifyInstance } from 'fastify';
import { z } from 'zod';
import { pool } from '../db.js';
import { requireAuth } from '../security/authz.js';
import { minio } from '../storage.js';

async function download(bucket:string,key:string,expiry=900){return minio.presignedGetObject(bucket,key,expiry);}
async function canManage(session:any,classId:string){if(session.role==='ADMIN')return true;const r=await pool.query(`select 1 from classes where id=$1 and teacher_user_id=$2`,[classId,session.sub]);return Boolean(r.rowCount);}

export async function registerBlueprintAcademicRoutes(app:FastifyInstance){
  app.post('/v1/admin/classes',async(request,reply)=>{const session=await requireAuth(request,reply,['ADMIN']);if(!session)return;const p=z.object({courseId:z.string().uuid(),cohortId:z.string().uuid().optional(),teacherUserId:z.string().uuid().optional(),name:z.string().min(2),startsAt:z.string().datetime().optional(),endsAt:z.string().datetime().optional()}).safeParse(request.body);if(!p.success)return reply.code(400).send({error:'invalid payload'});const d=p.data;const r=await pool.query(`insert into classes(course_id,cohort_id,teacher_user_id,name,starts_at,ends_at) values($1,$2,$3,$4,$5,$6) returning *`,[d.courseId,d.cohortId??null,d.teacherUserId??null,d.name,d.startsAt??null,d.endsAt??null]);if(d.cohortId)await pool.query(`insert into enrollments(class_id,student_user_id,status) select $1,user_id,'active' from students where cohort_id=$2 and status='ACTIVE' on conflict(class_id,student_user_id) do update set status='active'`,[r.rows[0].id,d.cohortId]);return reply.code(201).send(r.rows[0]);});

  app.get('/v1/academic/my/assignments',async(request,reply)=>{const session=await requireAuth(request,reply,['SANTRI']);if(!session)return;const r=await pool.query(`select a.id,a.title,a.description,a.due_at,a.max_score,a.allow_late,c.id class_id,c.name class_name,co.code course_code,co.name course_name,s.id submission_id,s.status submission_status,s.submitted_at,g.score,g.feedback,g.revision_required,g.revision_due_at,g.graded_at from enrollments e join classes c on c.id=e.class_id join courses co on co.id=c.course_id join assignments a on a.class_id=c.id left join submissions s on s.assignment_id=a.id and s.student_user_id=$1 left join grades g on g.submission_id=s.id where e.student_user_id=$1 and e.status='active' order by a.due_at nulls last,a.created_at desc`,[session.sub]);return{items:r.rows};});
  app.get('/v1/academic/classes/:classId/submissions',async(request,reply)=>{const session=await requireAuth(request,reply,['ADMIN','USTADZ']);if(!session)return;const{classId}=request.params as{classId:string};if(!await canManage(session,classId))return reply.code(403).send({error:'forbidden'});const r=await pool.query(`select s.id,s.status,s.notes,s.submitted_at,s.updated_at,s.student_user_id,u.full_name student_name,u.email,a.id assignment_id,a.title assignment_title,a.max_score,g.score,g.feedback,g.revision_required,g.revision_due_at,g.graded_at from submissions s join assignments a on a.id=s.assignment_id join users u on u.id=s.student_user_id left join grades g on g.submission_id=s.id where a.class_id=$1 order by case when s.status in('submitted','resubmitted') then 0 else 1 end,s.updated_at desc`,[classId]);return{items:r.rows};});
  app.get('/v1/academic/submissions/:id/files',async(request,reply)=>{const session=await requireAuth(request,reply);if(!session)return;const{id}=request.params as{id:string};const s=await pool.query(`select s.student_user_id,a.class_id,c.teacher_user_id from submissions s join assignments a on a.id=s.assignment_id join classes c on c.id=a.class_id where s.id=$1`,[id]);if(!s.rowCount)return reply.code(404).send({error:'submission not found'});const row=s.rows[0];if(session.role==='SANTRI'&&row.student_user_id!==session.sub)return reply.code(403).send({error:'forbidden'});if(session.role==='USTADZ'&&row.teacher_user_id!==session.sub)return reply.code(403).send({error:'forbidden'});const files=await pool.query(`select id,bucket,object_key,original_name,content_type,size_bytes,created_at from submission_files where submission_id=$1 order by created_at`,[id]);const items=[] as any[];for(const f of files.rows){let url:string|null=null;try{url=await download(f.bucket,f.object_key)}catch{}items.push({...f,url});}return{items};});

  app.get('/v1/academic/schedule',async(request,reply)=>{const session=await requireAuth(request,reply);if(!session)return;let r;if(session.role==='SANTRI')r=await pool.query(`select cs.*,c.name class_name,co.name course_name from class_sessions cs join classes c on c.id=cs.class_id join courses co on co.id=c.course_id join enrollments e on e.class_id=c.id where e.student_user_id=$1 and e.status='active' and cs.starts_at>=now()-interval '1 day' order by cs.starts_at limit 200`,[session.sub]);else if(session.role==='USTADZ')r=await pool.query(`select cs.*,c.name class_name,co.name course_name from class_sessions cs join classes c on c.id=cs.class_id join courses co on co.id=c.course_id where c.teacher_user_id=$1 and cs.starts_at>=now()-interval '7 days' order by cs.starts_at limit 200`,[session.sub]);else r=await pool.query(`select cs.*,c.name class_name,co.name course_name from class_sessions cs join classes c on c.id=cs.class_id join courses co on co.id=c.course_id where cs.starts_at>=now()-interval '7 days' order by cs.starts_at limit 500`);return{items:r.rows};});
  app.post('/v1/academic/classes/:classId/sessions',async(request,reply)=>{const session=await requireAuth(request,reply,['ADMIN','USTADZ']);if(!session)return;const{classId}=request.params as{classId:string};if(!await canManage(session,classId))return reply.code(403).send({error:'forbidden'});const p=z.object({title:z.string().min(2),startsAt:z.string().datetime(),endsAt:z.string().datetime().optional(),location:z.string().max(300).optional()}).safeParse(request.body);if(!p.success)return reply.code(400).send({error:'invalid payload'});const d=p.data;const r=await pool.query(`insert into class_sessions(class_id,title,starts_at,ends_at,location,created_by) values($1,$2,$3,$4,$5,$6) returning *`,[classId,d.title,d.startsAt,d.endsAt??null,d.location??null,session.sub]);return reply.code(201).send(r.rows[0]);});
  app.patch('/v1/academic/sessions/:id',async(request,reply)=>{const session=await requireAuth(request,reply,['ADMIN','USTADZ']);if(!session)return;const{id}=request.params as{id:string};const current=await pool.query(`select cs.class_id from class_sessions cs where cs.id=$1`,[id]);if(!current.rowCount)return reply.code(404).send({error:'session not found'});if(!await canManage(session,current.rows[0].class_id))return reply.code(403).send({error:'forbidden'});const p=z.object({title:z.string().min(2).optional(),startsAt:z.string().datetime().optional(),endsAt:z.string().datetime().nullable().optional(),location:z.string().nullable().optional(),status:z.enum(['SCHEDULED','RESCHEDULED','CANCELLED','COMPLETED']).optional()}).safeParse(request.body);if(!p.success)return reply.code(400).send({error:'invalid payload'});const d=p.data;const r=await pool.query(`update class_sessions set title=coalesce($2,title),starts_at=coalesce($3,starts_at),ends_at=case when $4::boolean then $5::timestamptz else ends_at end,location=case when $6::boolean then $7 else location end,status=coalesce($8,status),updated_at=now() where id=$1 returning *`,[id,d.title??null,d.startsAt??null,Object.prototype.hasOwnProperty.call(d,'endsAt'),d.endsAt??null,Object.prototype.hasOwnProperty.call(d,'location'),d.location??null,d.status??null]);return r.rows[0];});
  app.put('/v1/academic/sessions/:id/attendance',async(request,reply)=>{const session=await requireAuth(request,reply,['ADMIN','USTADZ']);if(!session)return;const{id}=request.params as{id:string};const s=await pool.query(`select class_id from class_sessions where id=$1`,[id]);if(!s.rowCount)return reply.code(404).send({error:'session not found'});if(!await canManage(session,s.rows[0].class_id))return reply.code(403).send({error:'forbidden'});const p=z.object({records:z.array(z.object({studentUserId:z.string().uuid(),status:z.enum(['PRESENT','ABSENT','LATE','EXCUSED']),notes:z.string().optional()})).min(1)}).safeParse(request.body);if(!p.success)return reply.code(400).send({error:'invalid attendance'});for(const rec of p.data.records){const e=await pool.query(`select 1 from enrollments where class_id=$1 and student_user_id=$2 and status='active'`,[s.rows[0].class_id,rec.studentUserId]);if(!e.rowCount)return reply.code(400).send({error:`student ${rec.studentUserId} is not enrolled`});await pool.query(`insert into attendance_records(session_id,student_user_id,status,notes,marked_by) values($1,$2,$3,$4,$5) on conflict(session_id,student_user_id) do update set status=excluded.status,notes=excluded.notes,marked_by=excluded.marked_by,marked_at=now()`,[id,rec.studentUserId,rec.status,rec.notes??null,session.sub]);}return{updated:p.data.records.length};});
  app.get('/v1/academic/my/attendance',async(request,reply)=>{const session=await requireAuth(request,reply,['SANTRI']);if(!session)return;const r=await pool.query(`select cs.title,cs.starts_at,c.name class_name,co.name course_name,ar.status,ar.notes,ar.marked_at from attendance_records ar join class_sessions cs on cs.id=ar.session_id join classes c on c.id=cs.class_id join courses co on co.id=c.course_id where ar.student_user_id=$1 order by cs.starts_at desc`,[session.sub]);return{items:r.rows};});

  app.post('/v1/admin/portfolio/:id/assets',async(request,reply)=>{const session=await requireAuth(request,reply,['ADMIN','USTADZ']);if(!session)return;const{id}=request.params as{id:string};const p=z.object({bucket:z.string().min(1),objectKey:z.string().min(1),assetType:z.string().default('file'),altText:z.string().optional(),sortOrder:z.number().int().default(0)}).safeParse(request.body);if(!p.success)return reply.code(400).send({error:'invalid payload'});const project=await pool.query(`select p.id,a.class_id from portfolio_projects p left join submissions s on s.id=p.submission_id left join assignments a on a.id=s.assignment_id where p.id=$1`,[id]);if(!project.rowCount)return reply.code(404).send({error:'portfolio not found'});if(session.role==='USTADZ'&&project.rows[0].class_id&&!await canManage(session,project.rows[0].class_id))return reply.code(403).send({error:'forbidden'});const r=await pool.query(`insert into portfolio_assets(portfolio_project_id,bucket,object_key,asset_type,alt_text,sort_order) values($1,$2,$3,$4,$5,$6) returning *`,[id,p.data.bucket,p.data.objectKey,p.data.assetType,p.data.altText??null,p.data.sortOrder]);return reply.code(201).send(r.rows[0]);});
  app.get('/v1/portfolio/:slug',async(request,reply)=>{const{slug}=request.params as{slug:string};const p=await pool.query(`select p.*,u.full_name student_name,a.title assignment_title,co.name course_name from portfolio_projects p join users u on u.id=p.student_user_id left join submissions s on s.id=p.submission_id left join assignments a on a.id=s.assignment_id left join classes c on c.id=a.class_id left join courses co on co.id=c.course_id where p.slug=$1 and p.featured=true and p.published_at is not null`,[slug]);if(!p.rowCount)return reply.code(404).send({error:'portfolio not found'});const assets=await pool.query(`select * from portfolio_assets where portfolio_project_id=$1 order by sort_order,created_at`,[p.rows[0].id]);const list=[] as any[];for(const a of assets.rows){let url:string|null=null;try{url=await download(a.bucket,a.object_key)}catch{}list.push({...a,url});}return{...p.rows[0],assets:list};});
  app.get('/v1/certificates/:number/verify',async(request,reply)=>{const{number}=request.params as{number:string};const r=await pool.query(`select c.certificate_no,c.title,c.issued_at,c.metadata,u.full_name student_name from certificates c join users u on u.id=c.student_user_id where c.certificate_no=$1`,[number]);if(!r.rowCount)return reply.code(404).send({valid:false});return{valid:true,...r.rows[0]};});
  app.get('/v1/academic/my/certificates',async(request,reply)=>{const session=await requireAuth(request,reply,['SANTRI']);if(!session)return;const r=await pool.query(`select * from certificates where student_user_id=$1 order by issued_at desc`,[session.sub]);const items=[] as any[];for(const c of r.rows){let downloadUrl:string|null=null;if(c.bucket&&c.object_key)try{downloadUrl=await download(c.bucket,c.object_key)}catch{}items.push({...c,downloadUrl});}return{items};});
}
