import type { FastifyInstance } from 'fastify';
import { z } from 'zod';
import { pool } from '../db.js';
import { requireAuth } from '../security/authz.js';

const period=z.object({name:z.string().min(3),cohortYear:z.number().int().min(2020).max(2100),opensAt:z.string().datetime().optional(),closesAt:z.string().datetime().optional(),capacity:z.number().int().positive().optional(),isActive:z.boolean().default(false)});
const application=z.object({admissionPeriodId:z.string().uuid(),applicantName:z.string().min(2),email:z.string().email(),phone:z.string().min(8).optional()});
const transition=z.object({status:z.enum(['ADMIN_VERIFIED','SCREENING','INTERVIEW'])});
const allowed:Record<string,string[]>={SUBMITTED:['ADMIN_VERIFIED'],ADMIN_VERIFIED:['SCREENING','INTERVIEW'],SCREENING:['INTERVIEW']};

export async function registerCompleteAdmissionRoutes(app:FastifyInstance){
  app.get('/v1/admissions/periods',async()=>{const r=await pool.query(`select * from admission_periods where is_active=true and (closes_at is null or closes_at>now()) order by cohort_year desc`);return{items:r.rows};});
  app.post('/v1/admissions/periods',async(request,reply)=>{const session=await requireAuth(request,reply,['ADMIN']);if(!session)return;const p=period.safeParse(request.body);if(!p.success)return reply.code(400).send({error:'invalid payload',issues:p.error.flatten()});const d=p.data;const r=await pool.query(`insert into admission_periods(name,cohort_year,opens_at,closes_at,capacity,is_active) values($1,$2,$3,$4,$5,$6) returning *`,[d.name,d.cohortYear,d.opensAt??null,d.closesAt??null,d.capacity??null,d.isActive]);return reply.code(201).send(r.rows[0]);});
  app.post('/v1/admissions/applications',async(request,reply)=>{const p=application.safeParse(request.body);if(!p.success)return reply.code(400).send({error:'invalid payload',issues:p.error.flatten()});const d=p.data;const open=await pool.query(`select id from admission_periods where id=$1 and is_active=true and (opens_at is null or opens_at<=now()) and (closes_at is null or closes_at>now())`,[d.admissionPeriodId]);if(!open.rowCount)return reply.code(400).send({error:'admission period is not open'});try{const r=await pool.query(`insert into applications(admission_period_id,applicant_name,email,phone,status,submitted_at) values($1,$2,lower($3),$4,'SUBMITTED',now()) returning *`,[d.admissionPeriodId,d.applicantName,d.email,d.phone??null]);return reply.code(201).send(r.rows[0]);}catch(e:any){if(e?.code==='23505')return reply.code(409).send({error:'application already exists for this period'});throw e;}});
  app.get('/v1/admissions/applications',async(request,reply)=>{const session=await requireAuth(request,reply,['ADMIN']);if(!session)return;const r=await pool.query(`select a.*,p.name period_name,p.cohort_year,pr.name program_name from applications a join admission_periods p on p.id=a.admission_period_id left join programs pr on pr.id=a.program_id order by a.created_at desc`);return{items:r.rows};});
  app.patch('/v1/admissions/applications/:id/status',async(request,reply)=>{const session=await requireAuth(request,reply,['ADMIN']);if(!session)return;const{id}=request.params as{id:string};const p=transition.safeParse(request.body);if(!p.success)return reply.code(400).send({error:'only administrative intermediate transitions are allowed here; decisions and enrollment use their dedicated endpoints'});const current=await pool.query(`select status from applications where id=$1`,[id]);if(!current.rowCount)return reply.code(404).send({error:'application not found'});if(!allowed[current.rows[0].status]?.includes(p.data.status))return reply.code(409).send({error:`invalid transition from ${current.rows[0].status} to ${p.data.status}`});const r=await pool.query(`update applications set status=$2::application_status,updated_at=now() where id=$1 returning id,status`,[id,p.data.status]);return r.rows[0];});
}
