import { randomUUID } from 'node:crypto';
import type { FastifyInstance } from 'fastify';
import { z } from 'zod';
import { pool,withTransaction } from '../db.js';
import { requireAuth } from '../security/authz.js';

const workspaceBase=()=>String(process.env.HERMES_WORKSPACE_BASE??'/srv/pmmi/workspaces').replace(/\/$/,'');
export async function registerFinalHermesRewardRoutes(app:FastifyInstance){
  app.get('/v1/hermes/profiles',async(request,reply)=>{const s=await requireAuth(request,reply);if(!s)return;const r=await pool.query(`select p.*,w.workspace_path,w.quota_bytes,w.archived_at from hermes_profiles p left join hermes_workspaces w on w.hermes_profile_id=p.id where p.user_id=$1 order by p.created_at desc`,[s.sub]);const e=await pool.query(`select hermes_agent_slots,storage_quota_bytes from resource_entitlements where user_id=$1`,[s.sub]);return{items:r.rows,entitlement:{slots:Number(e.rows[0]?.hermes_agent_slots??0),storageQuotaBytes:Number(e.rows[0]?.storage_quota_bytes??0)}};});
  app.post('/v1/hermes/build',async(request,reply)=>{const s=await requireAuth(request,reply);if(!s)return;const p=z.object({name:z.string().min(2).max(40).regex(/^[a-zA-Z0-9_-]+$/),role:z.string().max(40).default('general'),description:z.string().max(1000).optional()}).safeParse(request.body);if(!p.success)return reply.code(400).send({error:'invalid payload'});if(s.role==='SANTRI'){const st=await pool.query(`select status from students where user_id=$1`,[s.sub]);if(!st.rowCount||st.rows[0].status!=='ACTIVE')return reply.code(403).send({error:'only active santri can build agents'});}const e=await pool.query(`select hermes_agent_slots,storage_quota_bytes from resource_entitlements where user_id=$1`,[s.sub]);const active=Number((await pool.query(`select count(*) count from hermes_profiles where user_id=$1 and status not in('ARCHIVED','FAILED')`,[s.sub])).rows[0].count);if(active>=Number(e.rows[0]?.hermes_agent_slots??0))return reply.code(409).send({error:'no Hermes agent slot available'});const result=await withTransaction(async c=>{const name=`${s.role.toLowerCase()}-${s.sub.slice(0,8)}-${p.data.name}`;const pr=await c.query(`insert into hermes_profiles(user_id,profile_name,role,description) values($1,$2,$3,$4) returning *`,[s.sub,name,p.data.role,p.data.description??null]);const path=`${workspaceBase()}/${s.sub}/${pr.rows[0].id}`;await c.query(`insert into hermes_workspaces(hermes_profile_id,workspace_path,quota_bytes) values($1,$2,$3)`,[pr.rows[0].id,path,Number(e.rows[0]?.storage_quota_bytes??0)]);const j=await c.query(`insert into hermes_build_jobs(hermes_profile_id,job_type) values($1,'BUILD') returning *`,[pr.rows[0].id]);return{profile:pr.rows[0],workspacePath:path,job:j.rows[0]};});return reply.code(202).send(result);});
  app.post('/v1/hermes/profiles/:id/action',async(request,reply)=>{const s=await requireAuth(request,reply);if(!s)return;const{id}=request.params as{id:string};const p=z.object({action:z.enum(['START','STOP','ARCHIVE'])}).safeParse(request.body);if(!p.success)return reply.code(400).send({error:'invalid action'});if(!(await pool.query(`select 1 from hermes_profiles where id=$1 and user_id=$2`,[id,s.sub])).rowCount)return reply.code(404).send({error:'profile not found'});return reply.code(202).send((await pool.query(`insert into hermes_build_jobs(hermes_profile_id,job_type) values($1,$2) returning *`,[id,p.data.action])).rows[0]);});

  app.post('/v1/admin/rewards',async(request,reply)=>{const s=await requireAuth(request,reply,['ADMIN']);if(!s)return;const p=z.object({code:z.string().min(2),name:z.string().min(2),description:z.string().optional(),aiCredits:z.number().int().nonnegative().default(0),agentSlots:z.number().int().nonnegative().default(0),badge:z.string().optional()}).safeParse(request.body);if(!p.success)return reply.code(400).send({error:'invalid payload'});const d=p.data;return reply.code(201).send((await pool.query(`insert into rewards(code,name,description,ai_credits,agent_slots,badge) values(upper($1),$2,$3,$4,$5,$6) returning *`,[d.code,d.name,d.description??null,d.aiCredits,d.agentSlots,d.badge??null])).rows[0]);});
  app.post('/v1/admin/reward-rules',async(request,reply)=>{const s=await requireAuth(request,reply,['ADMIN']);if(!s)return;const p=z.object({rewardId:z.string().uuid(),eventType:z.string().min(2),criteria:z.record(z.unknown()).default({})}).safeParse(request.body);if(!p.success)return reply.code(400).send({error:'invalid payload'});return reply.code(201).send((await pool.query(`insert into reward_rules(reward_id,event_type,criteria) values($1,$2,$3::jsonb) returning *`,[p.data.rewardId,p.data.eventType,JSON.stringify(p.data.criteria)])).rows[0]);});
  app.get('/v1/rewards/achievements',async(request,reply)=>{const s=await requireAuth(request,reply);if(!s)return;return{items:(await pool.query(`select a.*,r.code,r.name,r.description,r.ai_credits,r.agent_slots,r.badge from achievements a join rewards r on r.id=a.reward_id where a.user_id=$1 order by a.earned_at desc`,[s.sub])).rows};});
  app.post('/v1/admin/rewards/evaluate-grade/:submissionId',async(request,reply)=>{const s=await requireAuth(request,reply,['ADMIN']);if(!s)return;const{submissionId}=request.params as{submissionId:string};const grade=await pool.query(`select sub.student_user_id,g.score,co.code course_code from submissions sub join grades g on g.submission_id=sub.id join assignments a on a.id=sub.assignment_id join classes c on c.id=a.class_id join courses co on co.id=c.course_id where sub.id=$1 and g.score is not null`,[submissionId]);if(!grade.rowCount)return reply.code(404).send({error:'graded submission not found'});const g=grade.rows[0];const rules=await pool.query(`select rr.id rule_id,rr.reward_id,rr.criteria,r.ai_credits,r.agent_slots from reward_rules rr join rewards r on r.id=rr.reward_id where rr.event_type='submission.graded' and rr.is_active=true and r.is_active=true`);const granted:string[]=[];for(const rule of rules.rows){const c=rule.criteria??{};if(Number(g.score)<Number(c.minScore??0)||(c.courseCode&&c.courseCode!==g.course_code))continue;try{const id=await withTransaction(async client=>{const a=await client.query(`insert into achievements(user_id,reward_rule_id,reward_id,source_type,source_id,metadata) values($1,$2,$3,'submission',$4,$5::jsonb) returning id`,[g.student_user_id,rule.rule_id,rule.reward_id,submissionId,JSON.stringify({score:Number(g.score),courseCode:g.course_code})]);const credits=Number(rule.ai_credits);if(credits>0){await client.query(`insert into ai_credit_wallets(user_id,balance) values($1,0) on conflict do nothing`,[g.student_user_id]);const w=await client.query(`select balance from ai_credit_wallets where user_id=$1 for update`,[g.student_user_id]);const after=Number(w.rows[0].balance)+credits;await client.query(`update ai_credit_wallets set balance=$1,updated_at=now() where user_id=$2`,[after,g.student_user_id]);await client.query(`insert into ai_credit_ledger(user_id,delta,balance_after,reason,source_type,source_id,idempotency_key) values($1,$2,$3,'reward','achievement',$4,$5)`,[g.student_user_id,credits,after,a.rows[0].id,`reward:${a.rows[0].id}`]);}if(Number(rule.agent_slots)>0)await client.query(`update resource_entitlements set hermes_agent_slots=hermes_agent_slots+$2,updated_at=now() where user_id=$1`,[g.student_user_id,Number(rule.agent_slots)]);return a.rows[0].id;});granted.push(id);}catch(e:any){if(e?.code!=='23505')throw e;}}return{granted};});
}
