import { createHash,randomBytes,randomUUID } from 'node:crypto';
import type { FastifyInstance,FastifyReply,FastifyRequest } from 'fastify';
import { z } from 'zod';
import { pool,withTransaction } from '../db.js';
import { requireAuth,type SessionUser } from '../security/authz.js';
import { writeAudit } from '../audit.js';

const hash=(v:string)=>createHash('sha256').update(v).digest('hex');
const base=()=>String(process.env.NINEROUTER_BASE_URL??'http://127.0.0.1:20128').replace(/\/$/,'');const upstreamKey=()=>process.env.NINEROUTER_API_KEY;const rpm=()=>Math.max(1,Number(process.env.AI_REQUESTS_PER_MINUTE??20));
async function session(request:FastifyRequest,reply:FastifyReply):Promise<SessionUser|null>{const a=request.headers.authorization;if(a?.startsWith('Bearer pmmi_')){const r=await pool.query(`select k.id,k.user_id,u.role,u.is_active from ai_api_keys k join users u on u.id=k.user_id where k.key_hash=$1 and k.revoked_at is null and (k.expires_at is null or k.expires_at>now())`,[hash(a.slice(7))]);if(!r.rowCount||!r.rows[0].is_active){reply.code(401).send({error:'invalid AI API key'});return null;}await pool.query(`update ai_api_keys set last_used_at=now() where id=$1`,[r.rows[0].id]);return{sub:r.rows[0].user_id,role:r.rows[0].role};}return requireAuth(request,reply);}
async function allowed(s:SessionUser,model:string){const r=await pool.query(`select enabled,model_pattern from ai_model_policies where role=$1 order by length(model_pattern) desc`,[s.role]);if(!r.rowCount)return true;const m=r.rows.filter(x=>model.startsWith(String(x.model_pattern).replace(/\*$/,'')));return m.length?m[0].enabled:false;}
async function rate(user:string){return Number((await pool.query(`select count(*) count from ai_usage_logs where user_id=$1 and created_at>now()-interval '1 minute'`,[user])).rows[0].count)<rpm();}
function conservativeCredits(messages:unknown,maxTokens:number){const bytes=Buffer.byteLength(JSON.stringify(messages),'utf8');const estimatedInput=Math.ceil(bytes/2);return Math.max(1,Math.ceil((estimatedInput+maxTokens)/1000));}
async function reserve(user:string,credits:number,requestId:string,model:string){return withTransaction(async c=>{await c.query(`insert into ai_credit_wallets(user_id,balance) values($1,0) on conflict do nothing`,[user]);const w=await c.query(`select balance from ai_credit_wallets where user_id=$1 for update`,[user]);const before=Number(w.rows[0].balance);if(before<credits)return null;const after=before-credits;await c.query(`update ai_credit_wallets set balance=$1,updated_at=now() where user_id=$2`,[after,user]);await c.query(`insert into ai_credit_ledger(user_id,delta,balance_after,reason,source_type,source_id,idempotency_key) values($1,$2,$3,'ai.reserve','ai_request',$4,$5)`,[user,-credits,after,requestId,`reserve:${requestId}`]);await c.query(`insert into ai_usage_logs(user_id,request_id,model,reserved_credits,status) values($1,$2,$3,$4,'RESERVED')`,[user,requestId,model,credits]);return{after};});}
async function reconcile(user:string,requestId:string,reserved:number,usage:any,status:'SUCCEEDED'|'FAILED',error?:string){const total=Number(usage?.total_tokens??0);const actual=status==='SUCCEEDED'?Math.max(1,Math.ceil(total/1000)):0;if(actual>reserved)throw new Error(`upstream usage exceeded conservative reservation (${actual}>${reserved})`);const refund=reserved-actual;return withTransaction(async c=>{const w=await c.query(`select balance from ai_credit_wallets where user_id=$1 for update`,[user]);let balance=Number(w.rows[0]?.balance??0);if(refund>0){balance+=refund;await c.query(`update ai_credit_wallets set balance=$1,updated_at=now() where user_id=$2`,[balance,user]);await c.query(`insert into ai_credit_ledger(user_id,delta,balance_after,reason,source_type,source_id,idempotency_key) values($1,$2,$3,'ai.reconcile','ai_request',$4,$5)`,[user,refund,balance,requestId,`reconcile:${requestId}`]);}await c.query(`update ai_usage_logs set input_tokens=$2,output_tokens=$3,total_tokens=$4,charged_credits=$5,status=$6,error=$7,completed_at=now() where request_id=$1`,[requestId,usage?.prompt_tokens??null,usage?.completion_tokens??null,total||null,actual,status,error??null]);if(status==='SUCCEEDED'&&balance<=5)await c.query(`insert into notification_outbox(event_type,source_type,source_id,payload,dedupe_key) values('ai.credit_low','ai_wallet',$1,jsonb_build_object('userId',$1::uuid,'balance',$2::bigint),$3) on conflict do nothing`,[user,balance,`ai-low:${user}:${balance}`]);return actual;});}
export async function registerFinalAIRoutes(app:FastifyInstance){
 const models=async(request:FastifyRequest,reply:FastifyReply)=>{if(!await session(request,reply))return;const headers:Record<string,string>={};if(upstreamKey())headers.authorization=`Bearer ${upstreamKey()}`;const r=await fetch(`${base()}/v1/models`,{headers});const text=await r.text();reply.code(r.status).header('content-type',r.headers.get('content-type')??'application/json').send(text);};app.get('/v1/ai/models',models);app.get('/v1/models',models);
 const chat=async(request:FastifyRequest,reply:FastifyReply)=>{const s=await session(request,reply);if(!s)return;const p=z.object({model:z.string().min(1),messages:z.array(z.object({role:z.string(),content:z.any()})).min(1),stream:z.boolean().default(false),max_tokens:z.number().int().positive().max(32768).optional()}).passthrough().safeParse(request.body);if(!p.success)return reply.code(400).send({error:'invalid OpenAI-compatible payload'});if(p.data.stream)return reply.code(400).send({error:'streaming is disabled until deterministic streaming reconciliation is available'});if(!await allowed(s,p.data.model))return reply.code(403).send({error:'model is not allowed for this role'});if(!await rate(s.sub))return reply.code(429).send({error:'AI rate limit exceeded'});const requestId=randomUUID();const reserved=conservativeCredits(p.data.messages,Number(p.data.max_tokens??2048));if(!await reserve(s.sub,reserved,requestId,p.data.model))return reply.code(402).send({error:'insufficient AI credits',required:reserved});try{const headers:Record<string,string>={'content-type':'application/json'};if(upstreamKey())headers.authorization=`Bearer ${upstreamKey()}`;const r=await fetch(`${base()}/v1/chat/completions`,{method:'POST',headers,body:JSON.stringify({...request.body,stream:false})});const text=await r.text();let data:any;try{data=JSON.parse(text)}catch{data={error:text}};if(!r.ok){await reconcile(s.sub,requestId,reserved,null,'FAILED',`9Router ${r.status}`);return reply.code(r.status).send(data);}const charged=await reconcile(s.sub,requestId,reserved,data.usage,'SUCCEEDED');reply.header('x-pmmi-request-id',requestId).header('x-pmmi-credits-reserved',String(reserved)).header('x-pmmi-credits-charged',String(charged));return data;}catch(e:any){const existing=await pool.query(`select status from ai_usage_logs where request_id=$1`,[requestId]);if(existing.rows[0]?.status==='RESERVED')await reconcile(s.sub,requestId,reserved,null,'FAILED',e?.message??String(e));return reply.code(502).send({error:'AI upstream unavailable'});}};app.post('/v1/ai/chat/completions',chat);app.post('/v1/chat/completions',chat);
 app.get('/v1/ai/wallet',async(request,reply)=>{const s=await requireAuth(request,reply);if(!s)return;const w=await pool.query(`select balance,updated_at from ai_credit_wallets where user_id=$1`,[s.sub]);const m=await pool.query(`select coalesce(sum(case when delta<0 then -delta else 0 end),0)::bigint spent,coalesce(sum(case when delta>0 then delta else 0 end),0)::bigint granted from ai_credit_ledger where user_id=$1 and created_at>=date_trunc('month',now())`,[s.sub]);return{balance:Number(w.rows[0]?.balance??0),updatedAt:w.rows[0]?.updated_at??null,month:m.rows[0]};});
 app.get('/v1/ai/ledger',async(request,reply)=>{const s=await requireAuth(request,reply);if(!s)return;return{items:(await pool.query(`select * from ai_credit_ledger where user_id=$1 order by created_at desc limit 200`,[s.sub])).rows};});
 app.post('/v1/admin/ai/credits/grant',async(request,reply)=>{const s=await requireAuth(request,reply,['ADMIN']);if(!s)return;const p=z.object({userId:z.string().uuid(),amount:z.number().int().positive(),reason:z.string().min(2)}).safeParse(request.body);if(!p.success)return reply.code(400).send({error:'invalid payload'});const result=await withTransaction(async c=>{await c.query(`insert into ai_credit_wallets(user_id,balance) values($1,0) on conflict do nothing`,[p.data.userId]);const w=await c.query(`select balance from ai_credit_wallets where user_id=$1 for update`,[p.data.userId]);const after=Number(w.rows[0].balance)+p.data.amount;await c.query(`update ai_credit_wallets set balance=$1 where user_id=$2`,[after,p.data.userId]);await c.query(`insert into ai_credit_ledger(user_id,delta,balance_after,reason,source_type,source_id,idempotency_key) values($1,$2,$3,$4,'admin',$5,$6)`,[p.data.userId,p.data.amount,after,p.data.reason,s.sub,`admin:${s.sub}:${randomUUID()}`]);await writeAudit(c,s.sub,'ai.credits_granted','user',p.data.userId,{amount:p.data.amount});return{balance:after};});return result;});
 app.post('/v1/ai/api-keys',async(request,reply)=>{const s=await requireAuth(request,reply);if(!s)return;const p=z.object({label:z.string().min(2).max(100),expiresAt:z.string().datetime().optional()}).safeParse(request.body);if(!p.success)return reply.code(400).send({error:'invalid payload'});const raw=`pmmi_${randomBytes(32).toString('base64url')}`;const r=await pool.query(`insert into ai_api_keys(user_id,key_hash,key_prefix,label,expires_at) values($1,$2,$3,$4,$5) returning id,key_prefix,label,created_at`,[s.sub,hash(raw),raw.slice(0,14),p.data.label,p.data.expiresAt??null]);return reply.code(201).send({...r.rows[0],apiKey:raw});});
 app.delete('/v1/ai/api-keys/:id',async(request,reply)=>{const s=await requireAuth(request,reply);if(!s)return;const{id}=request.params as{id:string};const r=await pool.query(`update ai_api_keys set revoked_at=now() where id=$1 and user_id=$2 and revoked_at is null returning id`,[id,s.sub]);if(!r.rowCount)return reply.code(404).send({error:'key not found'});return{revoked:true};});
 app.put('/v1/admin/ai/model-policies',async(request,reply)=>{const s=await requireAuth(request,reply,['ADMIN']);if(!s)return;const p=z.object({role:z.enum(['ADMIN','USTADZ','SANTRI']),modelPattern:z.string().min(1),enabled:z.boolean()}).safeParse(request.body);if(!p.success)return reply.code(400).send({error:'invalid payload'});return(await pool.query(`insert into ai_model_policies(role,model_pattern,enabled) values($1,$2,$3) on conflict(role,model_pattern) do update set enabled=excluded.enabled returning *`,[p.data.role,p.data.modelPattern,p.data.enabled])).rows[0];});
}
