import type { FastifyInstance } from 'fastify';
import { z } from 'zod';
import { pool, withTransaction } from '../db.js';
import { requireAuth } from '../security/authz.js';
import { createActivationToken } from './auth.js';
import { writeAudit } from '../audit.js';

const createSchema=z.object({email:z.string().email(),fullName:z.string().min(2),role:z.enum(['ADMIN','USTADZ']),aiCredits:z.number().int().min(0).default(0),hermesSlots:z.number().int().min(0).max(20).default(0),storageQuotaBytes:z.number().int().min(0).default(1073741824)});

export async function registerUserRoutes(app:FastifyInstance){
  app.get('/v1/admin/users',async(request,reply)=>{const admin=await requireAuth(request,reply,['ADMIN']);if(!admin)return;const q=z.object({role:z.enum(['ADMIN','USTADZ','SANTRI']).optional()}).safeParse(request.query);if(!q.success)return reply.code(400).send({error:'invalid query'});const result=await pool.query(`select u.id,u.email,u.full_name,u.role,u.is_active,u.created_at,re.ai_credit_balance,re.hermes_agent_slots,re.storage_quota_bytes,s.status student_status,s.student_number from users u left join resource_entitlements re on re.user_id=u.id left join students s on s.user_id=u.id where ($1::user_role is null or u.role=$1::user_role) order by u.created_at desc`,[q.data.role??null]);return {items:result.rows};});

  app.post('/v1/admin/users',async(request,reply)=>{const admin=await requireAuth(request,reply,['ADMIN']);if(!admin)return;const parsed=createSchema.safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:'invalid user',issues:parsed.error.flatten()});const d=parsed.data;try{const result=await withTransaction(async client=>{const user=await client.query(`insert into users(email,full_name,role,is_active) values(lower($1),$2,$3,false) returning id,email,full_name,role,is_active`,[d.email,d.fullName,d.role]);const id=user.rows[0].id;await client.query(`insert into resource_entitlements(user_id,ai_credit_balance,hermes_agent_slots,storage_quota_bytes) values($1,$2,$3,$4)`,[id,d.aiCredits,d.hermesSlots,d.storageQuotaBytes]);await client.query(`insert into ai_credit_wallets(user_id,balance) values($1,$2)`,[id,d.aiCredits]);if(d.aiCredits>0)await client.query(`insert into ai_credit_ledger(user_id,delta,balance_after,reason,reference_type,reference_id,idempotency_key,actor_user_id) values($1,$2,$2,'staff.initial_credit','user',$3,$4,$5)`,[id,d.aiCredits,id,`staff-credit:${id}`,admin.sub]);const activationToken=await createActivationToken(client,id);await writeAudit(client,admin.sub,'user.created','user',id,{role:d.role});return {...user.rows[0],activationToken};});return reply.code(201).send(result);}catch(error:any){if(error?.code==='23505')return reply.code(409).send({error:'email already exists'});throw error;}});

  app.post('/v1/admin/users/:id/activation',async(request,reply)=>{const admin=await requireAuth(request,reply,['ADMIN']);if(!admin)return;const {id}=request.params as {id:string};const exists=await pool.query(`select id from users where id=$1`,[id]);if(!exists.rowCount)return reply.code(404).send({error:'user not found'});const token=await withTransaction(async client=>{await client.query(`update account_activation_tokens set used_at=now() where user_id=$1 and used_at is null`,[id]);return createActivationToken(client,id);});return {activationToken:token};});

  app.patch('/v1/admin/users/:id/active',async(request,reply)=>{const admin=await requireAuth(request,reply,['ADMIN']);if(!admin)return;const {id}=request.params as {id:string};const parsed=z.object({isActive:z.boolean()}).safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:'isActive required'});const result=await pool.query(`update users set is_active=$1,updated_at=now() where id=$2 returning id,is_active`,[parsed.data.isActive,id]);if(!result.rowCount)return reply.code(404).send({error:'user not found'});return result.rows[0];});
}
