import { pool } from './db.js';

export async function scheduleBlueprintReminders(){
  const missing=await pool.query(`select a.id,a.email,a.phone,a.applicant_name from applications a where a.status='SUBMITTED' and a.submitted_at<now()-interval '24 hours' and not exists(select 1 from application_documents d where d.application_id=a.id and d.verification_status='VERIFIED')`);
  const day=new Date().toISOString().slice(0,10);
  for(const a of missing.rows)await pool.query(`insert into notification_outbox(event_type,source_type,source_id,payload,dedupe_key) values('admission.documents_missing','application',$1,jsonb_build_object('email',$2::text,'phone',$3::text,'applicantName',$4::text,'title','Berkas pendaftaran belum lengkap','body','Lengkapi dan unggah berkas pendaftaran PMMI agar proses seleksi dapat dilanjutkan.','channels',jsonb_build_array('EMAIL','WHATSAPP')),$5) on conflict do nothing`,[a.id,a.email,a.phone,a.applicant_name,`documents-missing:${a.id}:${day}`]);

  const registrations=await pool.query(`select a.id,a.email,a.phone,a.applicant_name,a.decision_at from applications a left join registrations r on r.application_id=a.id where a.status='ACCEPTED' and a.decision_at<now()-interval '3 days' and coalesce(r.status,'PENDING')<>'COMPLETED'`);
  for(const a of registrations.rows)await pool.query(`insert into notification_outbox(event_type,source_type,source_id,payload,dedupe_key) values('admission.registration_reminder','application',$1,jsonb_build_object('email',$2::text,'phone',$3::text,'applicantName',$4::text,'title','Pengingat daftar ulang PMMI','body','Kamu sudah diterima. Mohon selesaikan daftar ulang agar akun santri dapat diprovisikan.','channels',jsonb_build_array('EMAIL','WHATSAPP')),$5) on conflict do nothing`,[a.id,a.email,a.phone,a.applicant_name,`registration-reminder:${a.id}:${day}`]);

  const interviews=await pool.query(`select i.id,i.scheduled_at,i.location_or_url,a.email,a.phone,a.applicant_name from interviews i join applications a on a.id=i.application_id where i.status='SCHEDULED' and i.scheduled_at>now() and i.scheduled_at<=now()+interval '25 hours'`);
  for(const i of interviews.rows){const hours=(new Date(i.scheduled_at).getTime()-Date.now())/3600000;const tier=hours<=3.2?'3H':'H1';const label=tier==='3H'?'3 jam':'1 hari';await pool.query(`insert into notification_outbox(event_type,source_type,source_id,payload,dedupe_key) values('interview.reminder','interview',$1,jsonb_build_object('email',$2::text,'phone',$3::text,'applicantName',$4::text,'title','Pengingat wawancara PMMI','body',$5::text,'scheduledAt',$6::timestamptz,'locationOrUrl',$7::text,'channels',jsonb_build_array('EMAIL','WHATSAPP')),$8) on conflict do nothing`,[i.id,i.email,i.phone,i.applicant_name,`Wawancara dimulai sekitar ${label}${i.location_or_url?` — ${i.location_or_url}`:''}.`,i.scheduled_at,i.location_or_url??'',`interview-reminder:${i.id}:${tier}`]);}
}
