import test from 'node:test';
import assert from 'node:assert/strict';
import { pool } from './db.js';
import { evaluateRewards,processDelivery,processHermes,processOutbox,renderEvent } from './worker.js';
const uuid=()=>crypto.randomUUID();

test('sensitive lifecycle stays in-app until approved',()=>{assert.deepEqual(renderEvent('student.lifecycle',{to:'DROPOUT'}).channels,['IN_APP']);});
test('notification reward and Hermes pipelines',async()=>{const userId=uuid();const courseId=uuid();const classId=uuid();const assignmentId=uuid();const submissionId=uuid();try{await pool.query(`delete from notification_jobs;delete from notification_deliveries;delete from notifications;delete from notification_outbox;delete from notification_provider_health`);await pool.query(`insert into users(id,email,full_name,role,is_active) values($1,$2,'Worker Test','SANTRI',true)`,[userId,`worker-${Date.now()}@example.com`]);await pool.query(`insert into resource_entitlements(user_id,ai_credit_balance,hermes_agent_slots,storage_quota_bytes) values($1,0,1,1073741824)`,[userId]);await pool.query(`insert into ai_credit_wallets(user_id,balance) values($1,10)`,[userId]);await pool.query(`insert into user_notification_channels(user_id,channel,address_or_external_id,verified_at) values($1,'EMAIL',$2,now())`,[userId,`worker-${Date.now()}@example.com`]);
  await pool.query(`insert into notification_outbox(event_type,source_type,source_id,payload,dedupe_key) values('certificate.issued','test',$1,jsonb_build_object('userId',$1::uuid,'title','Certificate Test','certificateNo','TEST-1'),$2)`,[userId,`worker-notif-${Date.now()}`]);assert.equal(await processOutbox(),true);assert.equal(await processDelivery(),true);const sent=await pool.query(`select count(*)::int count from notification_deliveries d join notifications n on n.id=d.notification_id where n.user_id=$1 and d.channel='EMAIL' and d.status='SENT'`,[userId]);assert.equal(sent.rows[0].count,1);
  await pool.query(`insert into courses(id,code,name) values($1,$2,'Worker Course')`,[courseId,`W${Date.now()}`]);await pool.query(`insert into classes(id,course_id,name) values($1,$2,'Worker Class')`,[classId,courseId]);await pool.query(`insert into assignments(id,class_id,title,max_score) values($1,$2,'Reward Assignment',100)`,[assignmentId,classId]);await pool.query(`insert into submissions(id,assignment_id,student_user_id,status,submitted_at) values($1,$2,$3,'graded',now())`,[submissionId,assignmentId,userId]);await pool.query(`insert into grades(submission_id,score,revision_required,graded_at) values($1,95,false,now())`,[submissionId]);const reward=await pool.query(`insert into rewards(code,name,ai_credits,agent_slots) values($1,'Worker Reward',5,1) returning id`,[`WR${Date.now()}`]);await pool.query(`insert into reward_rules(reward_id,event_type,criteria) values($1,'submission.graded',$2::jsonb)`,[reward.rows[0].id,JSON.stringify({minScore:90})]);assert.ok(await evaluateRewards()>=1);assert.equal(Number((await pool.query(`select balance from ai_credit_wallets where user_id=$1`,[userId])).rows[0].balance),15);assert.equal(Number((await pool.query(`select hermes_agent_slots from resource_entitlements where user_id=$1`,[userId])).rows[0].hermes_agent_slots),2);
  const profile=await pool.query(`insert into hermes_profiles(user_id,profile_name,role) values($1,$2,'coder') returning id`,[userId,`santri-${Date.now()}`]);await pool.query(`insert into hermes_workspaces(hermes_profile_id,workspace_path,quota_bytes) values($1,$2,1000)`,[profile.rows[0].id,`/tmp/pmmi-worker/${userId}/${profile.rows[0].id}`]);await pool.query(`insert into hermes_build_jobs(hermes_profile_id,job_type) values($1,'BUILD')`,[profile.rows[0].id]);assert.equal(await processHermes(),true);const ready=await pool.query(`select status,ai_api_key_id from hermes_profiles where id=$1`,[profile.rows[0].id]);assert.equal(ready.rows[0].status,'READY');assert.ok(ready.rows[0].ai_api_key_id);
}finally{await pool.query(`delete from users where id=$1`,[userId]).catch(()=>{});await pool.end();}});
