import React,{useEffect,useState} from 'react';
import { api } from './api';

const Button=({children,onClick,type='button',kind='',disabled=false}:{children:React.ReactNode;onClick?:()=>void;type?:'button'|'submit';kind?:string;disabled?:boolean})=><button className={`btn ${kind}`} type={type} onClick={onClick} disabled={disabled}>{children}</button>;
const Json=({value}:{value:any})=><div className="code">{JSON.stringify(value,null,2)}</div>;
function useData(path:string){const [data,setData]=useState<any>(null);const [error,setError]=useState('');const load=async()=>{try{setError('');setData(await api(path));}catch(e:any){setError(e.message);}};useEffect(()=>{void load();},[path]);return{data,error,load};}

export function AdminStudentsPanel(){
  const students=useData('/v1/admin/users?role=SANTRI');const [message,setMessage]=useState('');const [draft,setDraft]=useState<Record<string,{title:string;body:string;channels:string[]}>>({});
  async function change(studentId:string,status:string){try{await api(`/v1/students/${studentId}/status`,{method:'PATCH',body:JSON.stringify({status})});setMessage(`Status berubah → ${status}`);await students.load();}catch(e:any){setMessage(e.message);}}
  async function communicate(studentId:string){const d=draft[studentId];if(!d?.title||!d?.body)return setMessage('Isi judul dan pesan formal terlebih dahulu.');try{await api(`/v1/students/${studentId}/lifecycle-communications`,{method:'POST',body:JSON.stringify({title:d.title,body:d.body,channels:d.channels?.length?d.channels:['EMAIL']})});setMessage('Komunikasi formal disetujui dan masuk outbox.');}catch(e:any){setMessage(e.message);}}
  return <div className="stack"><h2>Santri & Lifecycle</h2>{message&&<div className="notice">{message}</div>}{students.error&&<div className="notice error">{students.error}</div>}{students.data?.items?.map((s:any)=>{const sensitive=['DROPOUT','SUSPENDED','INACTIVE'].includes(s.student_status);const d=draft[s.student_id]??{title:`Pemberitahuan status PMMI`,body:'',channels:['EMAIL']};return <div className="card" key={s.id}><div className="sectionTitle"><div><h3>{s.full_name}</h3><div className="muted">{s.student_number} · {s.email} · {s.program_name??'-'} · {s.cohort_name??'-'}</div></div><span className="pill">{s.student_status??'UNKNOWN'}</span></div><div className="actions"><Button kind="secondary" onClick={()=>void change(s.student_id,'ACTIVE')}>ACTIVE</Button><Button kind="secondary" onClick={()=>void change(s.student_id,'GRADUATED')}>GRADUATED</Button><Button kind="secondary" onClick={()=>void change(s.student_id,'ALUMNI')}>ALUMNI</Button><Button kind="secondary" onClick={()=>void change(s.student_id,'SUSPENDED')}>SUSPENDED</Button><Button kind="danger" onClick={()=>void change(s.student_id,'DROPOUT')}>DROPOUT</Button></div>{sensitive&&<div className="form" style={{marginTop:14}}><div className="notice">Status sensitif tidak mengirim pesan otomatis ke santri. Review pesan di bawah lalu approve.</div><input placeholder="Judul formal" value={d.title} onChange={e=>setDraft({...draft,[s.student_id]:{...d,title:e.target.value}})}/><textarea placeholder="Isi komunikasi formal" value={d.body} onChange={e=>setDraft({...draft,[s.student_id]:{...d,body:e.target.value}})}/><div className="actions"><label><input type="checkbox" checked={d.channels.includes('EMAIL')} onChange={e=>setDraft({...draft,[s.student_id]:{...d,channels:e.target.checked?[...new Set([...d.channels,'EMAIL'])]:d.channels.filter(x=>x!=='EMAIL')}})}/> Email</label><label><input type="checkbox" checked={d.channels.includes('WHATSAPP')} onChange={e=>setDraft({...draft,[s.student_id]:{...d,channels:e.target.checked?[...new Set([...d.channels,'WHATSAPP'])]:d.channels.filter(x=>x!=='WHATSAPP')}})}/> WhatsApp</label><label><input type="checkbox" checked={d.channels.includes('TELEGRAM')} onChange={e=>setDraft({...draft,[s.student_id]:{...d,channels:e.target.checked?[...new Set([...d.channels,'TELEGRAM'])]:d.channels.filter(x=>x!=='TELEGRAM')}})}/> Telegram</label></div><Button onClick={()=>void communicate(s.student_id)}>Approve & Queue Communication</Button></div>}</div>})}</div>;
}

export function AdminHermesAuditPanel(){
  const hermes=useData('/v1/admin/hermes');const audit=useData('/v1/admin/audit-logs?limit=100');const [message,setMessage]=useState('');
  async function retry(id:string){try{const out=await api(`/v1/admin/hermes/${id}/retry`,{method:'POST'});setMessage(`Retry queued: ${out.jobId}`);await hermes.load();}catch(e:any){setMessage(e.message);}}
  async function archive(id:string){try{await api(`/v1/hermes/agents/${id}/archive`,{method:'POST'});setMessage('Archive queued');await hermes.load();}catch(e:any){setMessage(e.message);}}
  return <div className="stack"><h2>Hermes & Audit</h2>{message&&<div className="notice">{message}</div>}<div className="card"><h3>Hermes profiles</h3><div className="tableWrap"><table><thead><tr><th>User</th><th>Profile</th><th>Status</th><th>Workspace</th><th>Aksi</th></tr></thead><tbody>{hermes.data?.items?.map((p:any)=><tr key={p.id}><td>{p.full_name}<div className="muted">{p.email}</div></td><td>{p.display_name}<div className="muted">{p.profile_name}</div></td><td>{p.status}<div className="muted">{p.build_status??''}</div></td><td>{p.workspace_path}</td><td><div className="actions">{['FAILED','PENDING'].includes(p.status)&&<Button kind="secondary" onClick={()=>void retry(p.id)}>Retry</Button>}<Button kind="danger" onClick={()=>void archive(p.id)}>Archive</Button></div></td></tr>)}</tbody></table></div></div><div className="card"><h3>Audit log</h3><div className="tableWrap"><table><thead><tr><th>Waktu</th><th>Actor</th><th>Action</th><th>Entity</th></tr></thead><tbody>{audit.data?.items?.map((a:any)=><tr key={a.id}><td>{new Date(a.created_at).toLocaleString('id-ID')}</td><td>{a.actor_name??'system'}</td><td>{a.action}</td><td>{a.entity_type} {a.entity_id??''}</td></tr>)}</tbody></table></div></div></div>;
}

export function UstadzManagePanel(){
  const dash=useData('/v1/dashboard');const classes=dash.data?.classes??[];const [assignment,setAssignment]=useState({classId:'',title:'',description:'',dueAt:'',maxScore:100});const [session,setSession]=useState({classId:'',title:'',startsAt:'',endsAt:'',location:''});const [feature,setFeature]=useState<Record<string,{title:string;slug:string;summary:string}>>({});const [score,setScore]=useState<Record<string,string>>({});const [feedback,setFeedback]=useState<Record<string,string>>({});const [message,setMessage]=useState('');
  useEffect(()=>{if(classes[0]){setAssignment(a=>({...a,classId:a.classId||classes[0].id}));setSession(s=>({...s,classId:s.classId||classes[0].id}));}},[dash.data]);
  async function createAssignment(e:React.FormEvent){e.preventDefault();try{await api('/v1/academic/assignments',{method:'POST',body:JSON.stringify({...assignment,dueAt:assignment.dueAt?new Date(assignment.dueAt).toISOString():undefined})});setMessage('Assignment dibuat. Outbox akan membuat notification/reminder.');setAssignment({...assignment,title:'',description:''});}catch(e:any){setMessage(e.message);}}
  async function createSession(e:React.FormEvent){e.preventDefault();try{await api('/v1/academic/sessions',{method:'POST',body:JSON.stringify({...session,startsAt:new Date(session.startsAt).toISOString(),endsAt:new Date(session.endsAt).toISOString()})});setMessage('Jadwal kelas dibuat.');setSession({...session,title:'',startsAt:'',endsAt:'',location:''});}catch(e:any){setMessage(e.message);}}
  async function grade(id:string,revision:boolean){try{await api(`/v1/academic/submissions/${id}/grade`,{method:'POST',body:JSON.stringify({score:Number(score[id]??0),feedback:feedback[id]??'',revisionRequired:revision})});setMessage('Penilaian tersimpan.');await dash.load();}catch(e:any){setMessage(e.message);}}
  async function publish(id:string){const f=feature[id];if(!f?.title||!f?.slug)return setMessage('Isi title + slug untuk portfolio.');try{await api(`/v1/academic/submissions/${id}/feature`,{method:'POST',body:JSON.stringify(f)});setMessage('Featured: karya langsung public tanpa approval santri.');await dash.load();}catch(e:any){setMessage(e.message);}}
  return <div className="stack"><h2>Academic Workspace</h2>{message&&<div className="notice">{message}</div>}<div className="grid"><form className="card form" onSubmit={createAssignment}><h3>Buat assignment</h3><select value={assignment.classId} onChange={e=>setAssignment({...assignment,classId:e.target.value})}>{classes.map((c:any)=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input placeholder="Judul" value={assignment.title} onChange={e=>setAssignment({...assignment,title:e.target.value})}/><textarea placeholder="Instruksi" value={assignment.description} onChange={e=>setAssignment({...assignment,description:e.target.value})}/><input type="datetime-local" value={assignment.dueAt} onChange={e=>setAssignment({...assignment,dueAt:e.target.value})}/><Button type="submit">Buat assignment</Button></form><form className="card form" onSubmit={createSession}><h3>Buat jadwal kelas</h3><select value={session.classId} onChange={e=>setSession({...session,classId:e.target.value})}>{classes.map((c:any)=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input placeholder="Judul sesi" value={session.title} onChange={e=>setSession({...session,title:e.target.value})}/><input type="datetime-local" value={session.startsAt} onChange={e=>setSession({...session,startsAt:e.target.value})}/><input type="datetime-local" value={session.endsAt} onChange={e=>setSession({...session,endsAt:e.target.value})}/><input placeholder="Lokasi" value={session.location} onChange={e=>setSession({...session,location:e.target.value})}/><Button type="submit">Simpan jadwal</Button></form></div><h3>Submission menunggu review</h3>{dash.data?.pendingSubmissions?.map((s:any)=>{const f=feature[s.id]??{title:s.assignment_title??'',slug:'',summary:''};return <div className="card form" key={s.id}><div><strong>{s.assignment_title}</strong> · {s.student_name} · {s.class_name}</div><div className="formRow"><input type="number" placeholder="Nilai" value={score[s.id]??''} onChange={e=>setScore({...score,[s.id]:e.target.value})}/><input placeholder="Feedback" value={feedback[s.id]??''} onChange={e=>setFeedback({...feedback,[s.id]:e.target.value})}/></div><div className="actions"><Button onClick={()=>void grade(s.id,false)}>Grade</Button><Button kind="secondary" onClick={()=>void grade(s.id,true)}>Revision Required</Button></div><div className="formRow"><input placeholder="Portfolio title" value={f.title} onChange={e=>setFeature({...feature,[s.id]:{...f,title:e.target.value}})}/><input placeholder="slug-project" value={f.slug} onChange={e=>setFeature({...feature,[s.id]:{...f,slug:e.target.value}})}/><input placeholder="Summary" value={f.summary} onChange={e=>setFeature({...feature,[s.id]:{...f,summary:e.target.value}})}/></div><Button kind="secondary" onClick={()=>void publish(s.id)}>Feature → Publish Public</Button></div>})}</div>;
}

export function SantriAcademicPanel(){
  const schedule=useData('/v1/academic/schedule');const grades=useData('/v1/academic/my/grades');const certificates=useData('/v1/academic/my/certificates');const rewards=useData('/v1/rewards/my');
  return <div className="stack"><h2>Akademik Saya</h2><div className="card"><h3>Jadwal</h3>{schedule.data?.items?.map((s:any)=><div className="notification" key={s.id}><strong>{s.title??s.class_name}</strong><div>{new Date(s.starts_at).toLocaleString('id-ID')} – {new Date(s.ends_at).toLocaleString('id-ID')}</div><div className="muted">{s.course_name} · {s.location??s.meeting_url??'-'}</div></div>)}</div><div className="card"><h3>Nilai & Feedback</h3>{grades.data?.items?.map((g:any,index:number)=><div className="notification" key={g.id??index}><strong>{g.assignment_title}</strong><div>Nilai: {g.score??'-'} {g.revision_required?'· Revision Required':''}</div><div className="muted">{g.feedback??'Belum ada feedback'} {g.revision_due_at?`· Deadline revisi ${new Date(g.revision_due_at).toLocaleString('id-ID')}`:''}</div></div>)}</div><div className="grid"><div className="card"><h3>Sertifikat</h3>{certificates.data?.items?.map((c:any)=><div key={c.id} className="notification"><strong>{c.title}</strong><div>{c.certificate_no}</div><div className="muted">{new Date(c.issued_at).toLocaleDateString('id-ID')}</div></div>)}</div><div className="card"><h3>Achievements</h3>{rewards.data?.items?.map((r:any)=><div key={r.id} className="notification"><strong>{r.name}</strong><div className="muted">+{r.ai_credits} AI credits · +{r.hermes_slots} agent slot</div></div>)}</div></div></div>;
}

export function AdminAdmissionsDetailPanel(){
  const list=useData('/v1/admissions/applications');const [selected,setSelected]=useState<any>(null);const [message,setMessage]=useState('');const [score,setScore]=useState({category:'PORTFOLIO',score:0,maxScore:100,notes:''});const [interview,setInterview]=useState({scheduledAt:'',location:''});
  async function open(id:string){try{setSelected(await api(`/v1/admissions/applications/${id}`));}catch(e:any){setMessage(e.message);}}
  async function review(status:string){try{await api(`/v1/admissions/applications/${selected.id}/reviews`,{method:'POST',body:JSON.stringify({status,notes:'Reviewed from dashboard'})});setMessage(`Review: ${status}`);await open(selected.id);}catch(e:any){setMessage(e.message);}}
  async function saveScore(e:React.FormEvent){e.preventDefault();try{await api(`/v1/admissions/applications/${selected.id}/scores`,{method:'POST',body:JSON.stringify(score)});setMessage('Score tersimpan');await open(selected.id);}catch(e:any){setMessage(e.message);}}
  async function schedule(e:React.FormEvent){e.preventDefault();try{await api(`/v1/admissions/applications/${selected.id}/interviews`,{method:'POST',body:JSON.stringify({scheduledAt:new Date(interview.scheduledAt).toISOString(),location:interview.location})});setMessage('Interview dijadwalkan');await open(selected.id);}catch(e:any){setMessage(e.message);}}
  async function decision(decision:string){try{await api(`/v1/admissions/applications/${selected.id}/decision`,{method:'POST',body:JSON.stringify({decision,reason:'Keputusan panitia PMMI'})});setMessage(`Decision: ${decision}`);await open(selected.id);await list.load();}catch(e:any){setMessage(e.message);}}
  return <div className="stack"><h2>Admission Review</h2>{message&&<div className="notice">{message}</div>}<div className="grid"><div className="card"><h3>Applicant</h3>{list.data?.items?.map((a:any)=><button key={a.id} className="nav" style={{display:'block',width:'100%',marginTop:4}} onClick={()=>void open(a.id)}>{a.applicant_name} · {a.status}</button>)}</div>{selected&&<div className="card form"><h3>{selected.applicant_name}</h3><div className="muted">{selected.email} · {selected.status} · Documents {selected.documents?.length??0}</div><div className="actions"><Button kind="secondary" onClick={()=>void review('APPROVED')}>Approve docs</Button><Button kind="secondary" onClick={()=>void review('NEEDS_FIX')}>Needs fix</Button></div><form onSubmit={saveScore} className="form"><div className="formRow"><input value={score.category} onChange={e=>setScore({...score,category:e.target.value})}/><input type="number" value={score.score} onChange={e=>setScore({...score,score:Number(e.target.value)})}/><input type="number" value={score.maxScore} onChange={e=>setScore({...score,maxScore:Number(e.target.value)})}/></div><Button type="submit">Simpan score</Button></form><form onSubmit={schedule} className="form"><div className="formRow"><input type="datetime-local" value={interview.scheduledAt} onChange={e=>setInterview({...interview,scheduledAt:e.target.value})}/><input placeholder="Lokasi" value={interview.location} onChange={e=>setInterview({...interview,location:e.target.value})}/></div><Button type="submit">Jadwalkan interview</Button></form><div className="actions"><Button onClick={()=>void decision('ACCEPTED')}>ACCEPT</Button><Button kind="secondary" onClick={()=>void decision('WAITLISTED')}>WAITLIST</Button><Button kind="danger" onClick={()=>void decision('REJECTED')}>REJECT</Button></div><Json value={{documents:selected.documents,reviews:selected.reviews,scores:selected.scores,interviews:selected.interviews,registration:selected.registration}}/></div>}</div></div>;
}
