import React,{useEffect,useMemo,useState} from 'react';
import { api } from './api';
import AdminEnrollmentPanel from './AdminEnrollmentPanel';

const channels=['IN_APP','EMAIL','WHATSAPP','TELEGRAM'] as const;
const categories=['academic','admission','ai','rewards','lifecycle','ops','security'] as const;
const mandatory=new Set(['lifecycle','ops','security']);

function Button({children,onClick,type='button',kind='',disabled=false}:{children:React.ReactNode;onClick?:()=>void;type?:'button'|'submit';kind?:string;disabled?:boolean}){return <button className={`btn ${kind}`} type={type} onClick={onClick} disabled={disabled}>{children}</button>}
function useData(path:string){const [data,setData]=useState<any>(null);const [error,setError]=useState('');const load=async()=>{try{setError('');setData(await api(path));}catch(e:any){setError(e.message);}};useEffect(()=>{void load();},[path]);return{data,error,load};}


export function NotificationSettingsPanel(){
  const prefs=useData('/v1/notifications/preferences');const channelData=useData('/v1/notifications/channels');const [values,setValues]=useState<Record<string,boolean>>({});const [email,setEmail]=useState('');const [whatsapp,setWhatsapp]=useState('');const [message,setMessage]=useState('');
  useEffect(()=>{const next:Record<string,boolean>={};for(const category of categories)for(const channel of channels)next[`${category}:${channel}`]=true;for(const item of prefs.data?.items??[])next[`${item.category}:${item.channel}`]=Boolean(item.enabled);setValues(next);},[prefs.data]);
  async function savePrefs(){try{const payload=categories.flatMap(category=>channels.map(channel=>({category,channel,enabled:mandatory.has(category)?true:Boolean(values[`${category}:${channel}`])})));await api('/v1/notifications/preferences',{method:'PUT',body:JSON.stringify(payload)});setMessage('Preferensi notifikasi tersimpan.');await prefs.load();}catch(e:any){setMessage(e.message);}}
  async function saveChannel(channel:'EMAIL'|'WHATSAPP',address:string){try{await api('/v1/notifications/channels',{method:'PUT',body:JSON.stringify({channel,address,enabled:true})});setMessage(`${channel} tersimpan.`);await channelData.load();}catch(e:any){setMessage(e.message);}}
  async function telegram(){try{const link:any=await api('/v1/notifications/telegram/link-token',{method:'POST'});if(link.deepLink)window.open(link.deepLink,'_blank','noopener,noreferrer');else setMessage(`Telegram token: ${link.token}`);}catch(e:any){setMessage(e.message);}}
  return <div className="stack"><h2>Notification Settings</h2>{message&&<div className="notice">{message}</div>}<div className="card"><h3>Preferences</h3><div className="tableWrap"><table><thead><tr><th>Kategori</th>{channels.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{categories.map(category=><tr key={category}><td>{category}{mandatory.has(category)&&<div className="muted">mandatory</div>}</td>{channels.map(channel=><td key={channel}><input type="checkbox" disabled={mandatory.has(category)} checked={mandatory.has(category)?true:Boolean(values[`${category}:${channel}`])} onChange={e=>setValues({...values,[`${category}:${channel}`]:e.target.checked})}/></td>)}</tr>)}</tbody></table></div><Button onClick={()=>void savePrefs()}>Simpan preferences</Button></div><div className="grid"><div className="card form"><h3>Email</h3><input type="email" placeholder="email@domain.id" value={email} onChange={e=>setEmail(e.target.value)}/><Button onClick={()=>void saveChannel('EMAIL',email)} disabled={!email}>Simpan email</Button></div><div className="card form"><h3>WhatsApp</h3><input placeholder="62812..." value={whatsapp} onChange={e=>setWhatsapp(e.target.value)}/><Button onClick={()=>void saveChannel('WHATSAPP',whatsapp)} disabled={!whatsapp}>Simpan WhatsApp</Button></div><div className="card form"><h3>Telegram</h3><Button onClick={()=>void telegram()}>Hubungkan Telegram</Button></div></div><div className="card"><h3>Channel tersimpan</h3>{channelData.data?.items?.map((c:any)=><div className="notification" key={c.id}><strong>{c.channel}</strong> · {c.address_or_external_id}<div className="muted">{c.verified_at?'verified':'belum verified'} · {c.enabled?'enabled':'disabled'}</div></div>)}</div></div>;
}

export function AgentRuntimePanel(){
  const agents=useData('/v1/hermes/agents');const [message,setMessage]=useState('');async function action(id:string,kind:'start'|'stop'){try{await api(`/v1/hermes/agents/${id}/${kind}`,{method:'POST'});setMessage(`${kind==='start'?'Start':'Stop'} queued.`);await agents.load();}catch(e:any){setMessage(e.message);}}
  return <div className="stack"><h2>Agent Runtime Control</h2>{message&&<div className="notice">{message}</div>}{agents.data?.items?.map((a:any)=><div className="card" key={a.id}><div className="sectionTitle"><div><h3>{a.display_name}</h3><div className="muted">{a.profile_name}</div></div><span className="pill">{a.status}</span></div><div className="actions"><Button onClick={()=>void action(a.id,'start')} disabled={!['READY','STOPPED'].includes(a.status)}>Start</Button><Button kind="secondary" onClick={()=>void action(a.id,'stop')} disabled={!['READY','RUNNING'].includes(a.status)}>Stop</Button></div><div className="code">{a.workspace_path}</div></div>)}</div>;
}
