import React,{useMemo,useState} from 'react';
import { Link,useSearchParams } from 'react-router-dom';

const API_URL=(import.meta as any).env?.VITE_API_URL??'http://localhost:3001';

const ActivationPage:React.FC=()=>{
  const [params]=useSearchParams();const initial=useMemo(()=>params.get('token')??'',[params]);const [token,setToken]=useState(initial);const [password,setPassword]=useState('');const [confirm,setConfirm]=useState('');const [message,setMessage]=useState('');const [done,setDone]=useState(false);const [busy,setBusy]=useState(false);
  async function submit(e:React.FormEvent){e.preventDefault();if(password!==confirm)return setMessage('Konfirmasi password tidak sama.');setBusy(true);setMessage('');try{const r=await fetch(`${API_URL}/v1/auth/activate`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({token,password})});const body=await r.json();if(!r.ok)throw new Error(body.error??'Aktivasi gagal');setDone(true);setMessage('Akun aktif. Silakan login ke Digital Campus.');}catch(e:any){setMessage(e.message);}finally{setBusy(false);}}
  return <div className="min-h-screen pt-28 pb-20 px-6"><div className="max-w-xl mx-auto"><p className="text-fuchsia-400 font-semibold tracking-widest uppercase text-sm">Digital Campus</p><h1 className="text-4xl md:text-5xl font-bold mt-3">Aktivasi Akun</h1><p className="text-zinc-400 mt-4">Gunakan token aktivasi dari admin/enrollment dan buat password akun PMMI.</p>{message&&<div className={`mt-6 p-4 rounded-xl border ${done?'border-emerald-700 bg-emerald-950/50 text-emerald-200':'border-zinc-700 bg-zinc-950 text-zinc-200'}`}>{message}</div>}{done?<a href="https://app.pondokmultimedia.id" className="mt-6 inline-flex w-full justify-center py-3 rounded-xl bg-fuchsia-600 hover:bg-fuchsia-500 font-bold">Buka Dashboard</a>:<form onSubmit={submit} className="mt-8 space-y-5 p-7 rounded-2xl border border-zinc-800 bg-zinc-950/80"><label className="block"><span className="text-sm text-zinc-300">Token aktivasi</span><textarea required value={token} onChange={e=>setToken(e.target.value.trim())} className="mt-2 w-full bg-black border border-zinc-700 rounded-xl p-3 min-h-28"/></label><label className="block"><span className="text-sm text-zinc-300">Password baru</span><input required minLength={8} type="password" value={password} onChange={e=>setPassword(e.target.value)} className="mt-2 w-full bg-black border border-zinc-700 rounded-xl p-3"/></label><label className="block"><span className="text-sm text-zinc-300">Ulangi password</span><input required minLength={8} type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} className="mt-2 w-full bg-black border border-zinc-700 rounded-xl p-3"/></label><button disabled={busy} className="w-full py-3 rounded-xl bg-fuchsia-600 hover:bg-fuchsia-500 font-bold disabled:opacity-50">{busy?'Mengaktifkan…':'Aktifkan Akun'}</button></form>}<div className="mt-6 text-sm text-zinc-500"><Link to="/" className="hover:text-white">Kembali ke website PMMI</Link></div></div></div>;
};
export default ActivationPage;
